'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const gate=require('../expanded-reviewed-admissions-v6.cjs'),v5=require('../expanded-evidence-candidates-v5.cjs'),v6=require('../expanded-evidence-candidates-v6-r2.cjs');
const {stableJson,sha256}=require('../lossless-payload-sanitizer.cjs');
function example(){const raw={id:'inventory-source',type:'search',is_bundle:1,title:'Tudor\nWTB\nM79030B-0001\nReady in HK stock\nBrand New\nM79360N-0012 N2 36.5K\nWTB M79360N-0011'};const s={source_id:raw.id,source_hash:sha256(stableJson(raw)),source_system:'TEST',source_database:'TEST',source_table:'TEST',raw_payload:raw,canonicalization_version:'v1-json-keys-sorted-compact',hash_algorithm:'sha256'};return{s,p:{source_id:s.source_id,source_hash:s.source_hash,parent_source_field:'title',parent_field_hash:sha256(raw.title),parser_version:v6.PARSER_VERSION,disposition:'WHOLE_PARENT_INVENTORY_REBUILT_PENDING_REVIEW',supersedes_all_older_candidates_for_parent:true,previous_v5_witness_hashes:v5.buildExpandedCandidates(s).candidates.map(r=>r.candidate_hash),repaired_candidate_hashes:v6.buildExpandedCandidates(s).candidates.map(r=>r.candidate_hash)}};}
test('exact complete source rebuild retains all siblings and local intent/brand',()=>{const{s,p}=example(),r=gate.verifyInventoryParent(s,p);assert.equal(r.byHash.size,3);assert.deepEqual(r.output.candidates.map(r=>r.candidate.fields.intent),['WTB','WTS','WTB']);assert.equal(r.output.candidates[1].candidate.fields.brand,'Tudor');assert.equal(r.output.candidates[1].candidate.fields.original_price_currency,null);});
test('source mutation and incomplete/duplicated sibling sets are rejected',()=>{for(const change of [p=>p.repaired_candidate_hashes.pop(),p=>p.repaired_candidate_hashes.push(p.repaired_candidate_hashes[0]),p=>p.previous_v5_witness_hashes.pop(),p=>p.parser_version='expanded-evidence-v6-inventory-section',p=>p.supersedes_all_older_candidates_for_parent=false]){const{s,p}=example();change(p);assert.throws(()=>gate.verifyInventoryParent(s,p));}const{s,p}=example();s.raw_payload.title+=' changed';assert.throws(()=>gate.verifyInventoryParent(s,p));});
function coverage(){const census={status:'COMPLETE',counts:{parents:1527898,matched_parents:25874},parts:[{matches:{rows:25874}}]},counts={matched_parents:25874,changed_parents:25800,unchanged_parents:74,rebuilt_candidates:100000};const correction={status:'COMPLETE',admission_authority:false,binding:{contract:'WF_V6_WHOLE_PARENT_INVENTORY_CORRECTION_V1',limit_chunks:1},processed_chunks:[{chunk_index:0,census_part:census.parts[0],counts}],counts,correction_parts:[{original_parser_part_index:0,affected_parents:{rows:25800},changed_parents:25800,candidates:{rows:100000}}]};return{census,correction,frozen:{parent_rows:1527898,parts:Array.from({length:6112},()=>({}))}};}
test('coverage accounting and non-overlap are strict; fixture grants no admission',()=>{const c=coverage();gate.verifyInventoryCoverage(c.correction,c.census,c.frozen);for(const change of [c=>c.correction.processed_chunks.pop(),c=>c.correction.correction_parts.push(c.correction.correction_parts[0]),c=>c.correction.counts={...c.correction.counts,changed_parents:25799},c=>c.correction.correction_parts[0].candidates.rows++,c=>c.correction.binding.limit_chunks++,c=>c.correction.admission_authority=true]){const c=coverage();change(c);assert.throws(()=>gate.verifyInventoryCoverage(c.correction,c.census,c.frozen));}});
test('unsealed global prefix cannot reach any admission callback',async()=>{const fs=require('node:fs'),os=require('node:os'),path=require('node:path');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'wf-v6-admission-test-')),file=path.join(dir,'unsealed.json'),bytes=JSON.stringify({contract:gate.CONTRACT,status:'RUNNING'});fs.writeFileSync(file,bytes);let admissions=0;await assert.rejects(()=>gate.verifyReviewedAdmissionsV6({reviewManifestFile:file,expectedReviewManifestSha256:sha256(bytes),policyHashes:{},onAdmission:async()=>{admissions++;}}));assert.equal(admissions,0);});
