-- Dealer profile data remains private to authenticated application APIs.
-- Directory imports are staged and reviewed before any dealer is verified.

ALTER TABLE public.dealers
  ADD COLUMN IF NOT EXISTS slug TEXT,
  ADD COLUMN IF NOT EXISTS company_name TEXT,
  ADD COLUMN IF NOT EXISTS country_code TEXT,
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS rating NUMERIC(3,2),
  ADD COLUMN IF NOT EXISTS review_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS whatsapp_group_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS avatar_url TEXT,
  ADD COLUMN IF NOT EXISTS directory_url TEXT,
  ADD COLUMN IF NOT EXISTS directory_source_id TEXT,
  ADD COLUMN IF NOT EXISTS profile_summary TEXT,
  ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ;

ALTER TABLE public.dealers
  DROP CONSTRAINT IF EXISTS dealers_rating_range,
  ADD CONSTRAINT dealers_rating_range CHECK (rating IS NULL OR (rating >= 0 AND rating <= 5)),
  DROP CONSTRAINT IF EXISTS dealers_review_count_nonnegative,
  ADD CONSTRAINT dealers_review_count_nonnegative CHECK (review_count >= 0),
  DROP CONSTRAINT IF EXISTS dealers_group_count_nonnegative,
  ADD CONSTRAINT dealers_group_count_nonnegative CHECK (whatsapp_group_count >= 0);

CREATE UNIQUE INDEX IF NOT EXISTS idx_dealers_slug_unique
  ON public.dealers (lower(slug)) WHERE slug IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_dealers_directory_source_unique
  ON public.dealers (directory_source_id) WHERE directory_source_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_dealers_verified_rating
  ON public.dealers (rating DESC NULLS LAST, display_name)
  WHERE status = 'VERIFIED';

CREATE TABLE IF NOT EXISTS public.dealer_directory_import_staging (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system TEXT NOT NULL DEFAULT 'WATCHFACTS_RATED_DEALERS',
  source_id TEXT,
  display_name TEXT,
  company_name TEXT,
  phone_normalized TEXT,
  country_code TEXT,
  city TEXT,
  rating NUMERIC(3,2),
  review_count INTEGER,
  whatsapp_group_count INTEGER,
  avatar_url TEXT,
  directory_url TEXT,
  raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  comparison_status TEXT NOT NULL DEFAULT 'PENDING'
    CHECK (comparison_status IN ('PENDING', 'MATCHED', 'NEW', 'CONFLICT', 'REJECTED')),
  matched_dealer_id UUID REFERENCES public.dealers(id) ON DELETE SET NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dealer_directory_staging_status
  ON public.dealer_directory_import_staging (comparison_status, imported_at DESC);
DROP INDEX IF EXISTS public.idx_dealer_directory_staging_source;
CREATE UNIQUE INDEX idx_dealer_directory_staging_source
  ON public.dealer_directory_import_staging (source_system, source_id);

ALTER TABLE public.dealer_directory_import_staging ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.dealer_directory_import_staging FROM anon, authenticated;
GRANT ALL ON public.dealer_directory_import_staging TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

CREATE OR REPLACE VIEW public.dealer_profile_stats
WITH (security_invoker = true)
AS
WITH dated_posts AS (
  SELECT
    w.*,
    CASE
      WHEN w.listing_date ~ '^\d{4}-\d{2}-\d{2}'
        THEN left(w.listing_date, 10)::date::timestamptz
      ELSE w.created_at
    END AS observed_at
  FROM public.watch_records w
)
SELECT
  d.id AS dealer_id,
  count(w.id) AS total_posts,
  count(w.id) FILTER (WHERE w.listing_type = 'WTS') AS wts_posts,
  count(w.id) FILTER (WHERE w.listing_type IN ('WTB', 'NTQ')) AS wtb_posts,
  count(w.id) FILTER (
    WHERE w.listing_type = 'WTS'
      AND coalesce(w.listing_status, 'ACTIVE') NOT IN ('SOLD', 'WITHDRAWN', 'EXPIRED')
      AND coalesce(w.verdict, '') <> 'RECYCLE'
  ) AS active_listings,
  min(w.observed_at) AS first_post_at,
  max(w.observed_at) AS last_post_at,
  count(DISTINCT extract(year FROM w.observed_at)) AS posting_years
FROM public.dealers d
LEFT JOIN dated_posts w ON w.dealer_id = d.id
GROUP BY d.id;

REVOKE ALL ON public.dealer_profile_stats FROM anon, authenticated;
GRANT SELECT ON public.dealer_profile_stats TO service_role;

COMMENT ON TABLE public.dealer_directory_import_staging IS
  'Authenticated directory exports land here for deterministic comparison; staging never verifies or publishes a dealer automatically.';
COMMENT ON VIEW public.dealer_profile_stats IS
  'Dealer WTS, WTB/NTQ, activity, and posting-year counts derived from immutable listing lineage.';
