BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';

CREATE TABLE IF NOT EXISTS public.listing_identity_review_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_id TEXT NOT NULL REFERENCES public.watch_records(id) ON DELETE CASCADE,
  status TEXT NOT NULL,
  canonical_identity JSONB NOT NULL,
  evidence JSONB NOT NULL,
  reviewer_id TEXT,
  review_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.listing_image_review_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_object_key TEXT NOT NULL,
  record_id TEXT NOT NULL REFERENCES public.watch_records(id) ON DELETE CASCADE,
  status TEXT NOT NULL,
  identity_snapshot JSONB NOT NULL,
  evidence JSONB NOT NULL,
  reviewer_id TEXT,
  review_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.listing_identity_review_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listing_image_review_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.listing_identity_review_events FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.listing_image_review_events FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.listing_identity_review_events TO service_role;
GRANT ALL ON public.listing_image_review_events TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

CREATE OR REPLACE FUNCTION public.is_unsplit_bundle_parent(p_source_record_id TEXT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.normalization_shadow_v4 shadow
    WHERE shadow.source_record_id = p_source_record_id
      AND (
        shadow.candidate_count > 1
        OR 'BUNDLE_SPLIT_REQUIRED' = ANY(COALESCE(shadow.change_flags, ARRAY[]::TEXT[]))
      )
  );
$$;

CREATE OR REPLACE FUNCTION public.is_verified_listing_dealer_lineage(
  p_record_id TEXT,
  p_dealer_id UUID
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.seller_listing_lineage_staging s
    WHERE s.source_record_id = p_record_id
      AND s.matched_dealer_id = p_dealer_id
      AND s.match_status = 'APPLIED'
  );
$$;

REVOKE ALL ON FUNCTION public.is_unsplit_bundle_parent(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_verified_listing_dealer_lineage(TEXT, UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_unsplit_bundle_parent(TEXT) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_verified_listing_dealer_lineage(TEXT, UUID) TO service_role;

CREATE OR REPLACE FUNCTION public.verified_listing_thumbnail(p_record_id TEXT)
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH expected AS (
    SELECT
      w.id,
      COALESCE(NULLIF(r.canonical_brand, ''), w.brand) AS brand,
      COALESCE(NULLIF(r.canonical_model, ''), w.model) AS model,
      COALESCE(NULLIF(r.canonical_reference, ''), w.reference) AS reference,
      COALESCE(NULLIF(r.canonical_dial_color, ''), w.dial_color) AS dial_color
    FROM public.watch_records w
    JOIN public.listing_identity_reviews r
      ON r.record_id = w.id
     AND r.status IN ('CATALOG_CONFIRMED', 'HUMAN_APPROVED')
    WHERE w.id = p_record_id
  )
  SELECT m.public_url
  FROM expected x
  JOIN public.listing_image_reviews r ON r.record_id = x.id
  JOIN public.media_manifest m
    ON m.source_object_key = r.source_object_key
   AND m.matched_record_id = r.record_id
  WHERE r.status = 'VISUALLY_VERIFIED'
    AND lower(trim(r.identity_snapshot->>'brand')) = lower(trim(x.brand))
    AND lower(trim(r.identity_snapshot->>'model')) = lower(trim(x.model))
    AND lower(trim(r.identity_snapshot->>'reference')) = lower(trim(x.reference))
    AND lower(trim(r.identity_snapshot->>'dial_color')) = lower(trim(x.dial_color))
  ORDER BY r.reviewed_at DESC NULLS LAST, r.source_object_key
  LIMIT 1;
$$;

CREATE OR REPLACE VIEW public.trading_floor_verified_listings
WITH (security_invoker = true) AS
SELECT
  m.id,
  COALESCE(NULLIF(r.canonical_brand, ''), w.brand) AS brand,
  COALESCE(NULLIF(r.canonical_reference, ''), w.reference) AS reference,
  COALESCE(NULLIF(r.canonical_dial_color, ''), w.dial_color) AS dial_color,
  m.condition,
  m.year,
  m.price_raw,
  m.price_usd,
  m.currency,
  m.confidence,
  m.verdict,
  m.source,
  m.source_type,
  m.listing_type,
  m.listing_date,
  m.listing_status,
  m.created_at,
  public.verified_listing_thumbnail(m.id) IS NOT NULL AS has_images,
  public.verified_listing_thumbnail(m.id) AS thumbnail_url,
  m.region,
  COALESCE(NULLIF(r.canonical_model, ''), w.model) AS model,
  CASE
    WHEN public.verified_listing_thumbnail(m.id) IS NULL THEN '[]'::jsonb
    ELSE jsonb_build_array(public.verified_listing_thumbnail(m.id))
  END AS image_urls
FROM public.trading_floor_market_listings m
JOIN public.watch_records w ON w.id = m.id
JOIN public.listing_identity_reviews r
  ON r.record_id = m.id
 AND r.status IN ('CATALOG_CONFIRMED', 'HUMAN_APPROVED');

GRANT SELECT ON public.trading_floor_verified_listings TO anon, authenticated;

CREATE OR REPLACE VIEW public.price_research_verified_source
WITH (security_invoker = true) AS
SELECT
  w.id,
  COALESCE(NULLIF(r.canonical_brand, ''), w.brand) AS brand,
  COALESCE(NULLIF(r.canonical_model, ''), w.model) AS model,
  COALESCE(NULLIF(r.canonical_reference, ''), w.reference) AS reference,
  COALESCE(NULLIF(r.canonical_dial_color, ''), w.dial_color) AS dial_color,
  w.price_raw,
  w.price_usd,
  w.currency,
  w.raw_message,
  w.flags,
  w.created_at,
  w.listing_date,
  w.condition,
  w.source,
  w.year,
  w.listing_type,
  w.dealer_id,
  w.confidence,
  w.thumbnail_url,
  w.image_urls,
  w.has_images,
  w.verdict,
  w.listing_status
FROM public.watch_records w
JOIN public.listing_identity_reviews r
  ON r.record_id = w.id
 AND r.status IN ('CATALOG_CONFIRMED', 'HUMAN_APPROVED')
WHERE NOT public.is_unsplit_bundle_parent(w.id)
  AND w.listing_type IS DISTINCT FROM 'MULTI'
  AND COALESCE(w.verdict, 'HUMAN') <> 'RECYCLE'
  AND COALESCE(w.listing_status, 'ACTIVE') NOT IN ('HIDDEN', 'REJECTED', 'DELETED');

REVOKE ALL ON public.price_research_verified_source FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.price_research_verified_source TO service_role;

CREATE OR REPLACE VIEW public.verified_dealer_profile_stats
WITH (security_invoker = true) AS
WITH verified_posts AS (
  SELECT
    w.*,
    CASE
      WHEN w.listing_date ~ '^\d{4}-\d{2}-\d{2}'
        THEN left(w.listing_date, 10)::date::timestamptz
      ELSE NULL
    END AS observed_at
  FROM public.watch_records w
  JOIN public.listing_identity_reviews r
    ON r.record_id = w.id
   AND r.status IN ('CATALOG_CONFIRMED', 'HUMAN_APPROVED')
  WHERE w.dealer_id IS NOT NULL
    AND public.is_verified_listing_dealer_lineage(w.id, w.dealer_id)
    AND w.listing_type IS DISTINCT FROM 'MULTI'
    AND NOT public.is_unsplit_bundle_parent(w.id)
    AND COALESCE(w.verdict, 'HUMAN') <> 'RECYCLE'
    AND COALESCE(w.listing_status, 'ACTIVE') NOT IN ('HIDDEN', 'REJECTED', 'DELETED')
)
SELECT
  d.id AS dealer_id,
  count(w.id) AS total_posts,
  count(w.id) FILTER (WHERE w.listing_type = 'WTS') AS wts_posts,
  count(w.id) FILTER (WHERE w.listing_type IN ('WTB', 'NTQ')) AS wtb_posts,
  count(w.id) FILTER (
    WHERE w.listing_type = 'WTS'
      AND COALESCE(w.listing_status, 'ACTIVE') NOT IN ('SOLD', 'WITHDRAWN', 'EXPIRED')
  ) AS active_listings,
  min(w.observed_at) AS first_post_at,
  max(w.observed_at) AS last_post_at,
  count(DISTINCT extract(year FROM w.observed_at)) AS posting_years
FROM public.dealers d
LEFT JOIN verified_posts w ON w.dealer_id = d.id
WHERE d.status = 'VERIFIED'
  AND d.contact_consent IS TRUE
GROUP BY d.id;

REVOKE ALL ON public.verified_dealer_profile_stats FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.verified_dealer_profile_stats TO service_role;

CREATE OR REPLACE FUNCTION public.apply_listing_identity_review(
  p_record_id TEXT,
  p_decision TEXT,
  p_operator_id TEXT,
  p_reason TEXT,
  p_canonical JSONB DEFAULT '{}'::jsonb,
  p_evidence JSONB DEFAULT '{}'::jsonb
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_decision TEXT := upper(trim(COALESCE(p_decision, '')));
BEGIN
  IF v_decision NOT IN ('HUMAN_APPROVED', 'CONFLICT') THEN
    RAISE EXCEPTION 'Human decisions must be HUMAN_APPROVED or CONFLICT';
  END IF;
  IF NULLIF(trim(p_operator_id), '') IS NULL OR NULLIF(trim(p_reason), '') IS NULL THEN
    RAISE EXCEPTION 'operator_id and reason are required';
  END IF;
  IF p_evidence IS NULL OR p_evidence = '{}'::jsonb THEN
    RAISE EXCEPTION 'Nonempty source evidence is required';
  END IF;
  IF v_decision = 'HUMAN_APPROVED' AND (
    NULLIF(trim(p_canonical->>'brand'), '') IS NULL
    OR NULLIF(trim(p_canonical->>'model'), '') IS NULL
    OR NULLIF(trim(p_canonical->>'reference'), '') IS NULL
    OR NULLIF(trim(p_canonical->>'dial_color'), '') IS NULL
  ) THEN
    RAISE EXCEPTION 'Human approval requires canonical brand, model, reference, and dial_color';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.watch_records WHERE id = p_record_id) THEN
    RAISE EXCEPTION 'Listing not found';
  END IF;

  INSERT INTO public.listing_identity_review_events (
    record_id, status, canonical_identity, evidence, reviewer_id, review_reason
  ) VALUES (
    p_record_id, v_decision, COALESCE(p_canonical, '{}'::jsonb),
    p_evidence, p_operator_id, p_reason
  );

  INSERT INTO public.listing_identity_reviews (
    record_id, status, canonical_brand, canonical_model, canonical_reference,
    canonical_dial_color, evidence, reviewer_id, review_reason, reviewed_at, updated_at
  ) VALUES (
    p_record_id, v_decision, p_canonical->>'brand', p_canonical->>'model',
    p_canonical->>'reference', p_canonical->>'dial_color', p_evidence,
    p_operator_id, p_reason, now(), now()
  )
  ON CONFLICT (record_id) DO UPDATE SET
    status = EXCLUDED.status,
    canonical_brand = EXCLUDED.canonical_brand,
    canonical_model = EXCLUDED.canonical_model,
    canonical_reference = EXCLUDED.canonical_reference,
    canonical_dial_color = EXCLUDED.canonical_dial_color,
    evidence = EXCLUDED.evidence,
    reviewer_id = EXCLUDED.reviewer_id,
    review_reason = EXCLUDED.review_reason,
    reviewed_at = EXCLUDED.reviewed_at,
    updated_at = now();

  RETURN jsonb_build_object(
    'record_id', p_record_id,
    'status', v_decision,
    'customer_publishable', v_decision = 'HUMAN_APPROVED'
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.apply_listing_image_review(
  p_source_object_key TEXT,
  p_record_id TEXT,
  p_decision TEXT,
  p_operator_id TEXT,
  p_reason TEXT,
  p_identity_snapshot JSONB,
  p_evidence JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_decision TEXT := upper(trim(COALESCE(p_decision, '')));
  v_manifest public.media_manifest;
  v_expected JSONB;
  v_visual_match TEXT := upper(trim(COALESCE(p_evidence->>'visual_match', '')));
BEGIN
  IF v_decision NOT IN ('VISUALLY_VERIFIED', 'REJECTED') THEN
    RAISE EXCEPTION 'Image decisions must be VISUALLY_VERIFIED or REJECTED';
  END IF;
  IF NULLIF(trim(p_operator_id), '') IS NULL OR NULLIF(trim(p_reason), '') IS NULL THEN
    RAISE EXCEPTION 'operator_id and reason are required';
  END IF;
  IF (v_decision = 'VISUALLY_VERIFIED' AND v_visual_match <> 'MATCH')
    OR (v_decision = 'REJECTED' AND v_visual_match <> 'NO_MATCH') THEN
    RAISE EXCEPTION 'visual_match must be MATCH for approval or NO_MATCH for rejection';
  END IF;

  SELECT * INTO v_manifest
  FROM public.media_manifest
  WHERE source_object_key = p_source_object_key
  FOR UPDATE;

  IF NOT FOUND OR v_manifest.matched_record_id IS DISTINCT FROM p_record_id THEN
    RAISE EXCEPTION 'Manifest ownership does not match the reviewed listing';
  END IF;

  SELECT jsonb_build_object(
    'brand', COALESCE(NULLIF(r.canonical_brand, ''), w.brand),
    'model', COALESCE(NULLIF(r.canonical_model, ''), w.model),
    'reference', COALESCE(NULLIF(r.canonical_reference, ''), w.reference),
    'dial_color', COALESCE(NULLIF(r.canonical_dial_color, ''), w.dial_color)
  )
  INTO v_expected
  FROM public.watch_records w
  JOIN public.listing_identity_reviews r
    ON r.record_id = w.id
   AND r.status IN ('CATALOG_CONFIRMED', 'HUMAN_APPROVED')
  WHERE w.id = p_record_id;

  IF v_decision = 'VISUALLY_VERIFIED' AND (
    v_expected IS NULL
    OR lower(trim(p_identity_snapshot->>'brand')) IS DISTINCT FROM lower(trim(v_expected->>'brand'))
    OR lower(trim(p_identity_snapshot->>'model')) IS DISTINCT FROM lower(trim(v_expected->>'model'))
    OR lower(trim(p_identity_snapshot->>'reference')) IS DISTINCT FROM lower(trim(v_expected->>'reference'))
    OR lower(trim(p_identity_snapshot->>'dial_color')) IS DISTINCT FROM lower(trim(v_expected->>'dial_color'))
  ) THEN
    RAISE EXCEPTION 'Image identity snapshot does not match the current verified listing identity';
  END IF;

  INSERT INTO public.listing_image_review_events (
    source_object_key, record_id, status, identity_snapshot, evidence,
    reviewer_id, review_reason
  ) VALUES (
    p_source_object_key, p_record_id, v_decision,
    COALESCE(p_identity_snapshot, '{}'::jsonb), p_evidence,
    p_operator_id, p_reason
  );

  INSERT INTO public.listing_image_reviews (
    source_object_key, record_id, status, identity_snapshot, evidence,
    reviewer_id, review_reason, reviewed_at, updated_at
  ) VALUES (
    p_source_object_key, p_record_id, v_decision,
    COALESCE(p_identity_snapshot, '{}'::jsonb), p_evidence,
    p_operator_id, p_reason, now(), now()
  )
  ON CONFLICT (source_object_key) DO UPDATE SET
    record_id = EXCLUDED.record_id,
    status = EXCLUDED.status,
    identity_snapshot = EXCLUDED.identity_snapshot,
    evidence = EXCLUDED.evidence,
    reviewer_id = EXCLUDED.reviewer_id,
    review_reason = EXCLUDED.review_reason,
    reviewed_at = EXCLUDED.reviewed_at,
    updated_at = now();

  RETURN jsonb_build_object(
    'source_object_key', p_source_object_key,
    'record_id', p_record_id,
    'status', v_decision,
    'customer_visible', v_decision = 'VISUALLY_VERIFIED'
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.stage_listing_identity_classifications(p_rows JSONB)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row JSONB;
  v_status TEXT;
  v_written INTEGER := 0;
  v_preserved INTEGER := 0;
BEGIN
  IF jsonb_typeof(p_rows) <> 'array' OR jsonb_array_length(p_rows) > 1000 THEN
    RAISE EXCEPTION 'Identity staging payload must be an array of at most 1000 rows';
  END IF;

  FOR v_row IN SELECT value FROM jsonb_array_elements(p_rows)
  LOOP
    v_status := upper(trim(COALESCE(v_row->>'status', '')));
    IF v_status NOT IN ('UNVERIFIED', 'CATALOG_CONFIRMED', 'CONFLICT') THEN
      RAISE EXCEPTION 'Automated staging cannot create human approval';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.watch_records WHERE id = v_row->>'record_id') THEN
      CONTINUE;
    END IF;
    IF EXISTS (
      SELECT 1 FROM public.listing_identity_reviews
      WHERE record_id = v_row->>'record_id'
        AND (reviewer_id IS NOT NULL OR reviewed_at IS NOT NULL)
    ) THEN
      v_preserved := v_preserved + 1;
      CONTINUE;
    END IF;

    INSERT INTO public.listing_identity_reviews (
      record_id, status, canonical_brand, canonical_model, canonical_reference,
      canonical_dial_color, evidence, updated_at
    ) VALUES (
      v_row->>'record_id', v_status, v_row->>'canonical_brand',
      v_row->>'canonical_model', v_row->>'canonical_reference',
      v_row->>'canonical_dial_color', COALESCE(v_row->'evidence', '{}'::jsonb), now()
    )
    ON CONFLICT (record_id) DO UPDATE SET
      status = EXCLUDED.status,
      canonical_brand = EXCLUDED.canonical_brand,
      canonical_model = EXCLUDED.canonical_model,
      canonical_reference = EXCLUDED.canonical_reference,
      canonical_dial_color = EXCLUDED.canonical_dial_color,
      evidence = EXCLUDED.evidence,
      updated_at = now()
    WHERE public.listing_identity_reviews.reviewer_id IS NULL
      AND public.listing_identity_reviews.reviewed_at IS NULL;
    IF FOUND THEN v_written := v_written + 1; END IF;
  END LOOP;

  RETURN jsonb_build_object('written', v_written, 'human_decisions_preserved', v_preserved);
END;
$$;

REVOKE ALL ON FUNCTION public.apply_listing_identity_review(TEXT, TEXT, TEXT, TEXT, JSONB, JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.apply_listing_image_review(TEXT, TEXT, TEXT, TEXT, TEXT, JSONB, JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.stage_listing_identity_classifications(JSONB) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.apply_listing_identity_review(TEXT, TEXT, TEXT, TEXT, JSONB, JSONB) TO service_role;
GRANT EXECUTE ON FUNCTION public.apply_listing_image_review(TEXT, TEXT, TEXT, TEXT, TEXT, JSONB, JSONB) TO service_role;
GRANT EXECUTE ON FUNCTION public.stage_listing_identity_classifications(JSONB) TO service_role;

NOTIFY pgrst, 'reload schema';
COMMIT;
