-- Verified dealer/poster lineage. Historical rows remain unresolved until a
-- source identity is matched explicitly; this migration never guesses from
-- free-form message text.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.dealers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  display_name TEXT,
  status TEXT NOT NULL DEFAULT 'UNVERIFIED'
    CHECK (status IN ('UNVERIFIED', 'VERIFIED', 'SUSPENDED', 'ARCHIVED')),
  contact_consent BOOLEAN NOT NULL DEFAULT false,
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.dealer_source_identities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dealer_id UUID NOT NULL REFERENCES public.dealers(id) ON DELETE CASCADE,
  source_system TEXT NOT NULL,
  source_identity TEXT NOT NULL,
  identity_type TEXT NOT NULL,
  verification_status TEXT NOT NULL DEFAULT 'UNVERIFIED'
    CHECK (verification_status IN ('UNVERIFIED', 'VERIFIED', 'REJECTED')),
  first_seen_at TIMESTAMPTZ,
  last_seen_at TIMESTAMPTZ,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (source_system, source_identity, identity_type)
);

ALTER TABLE public.watch_records
  ADD COLUMN IF NOT EXISTS dealer_id UUID REFERENCES public.dealers(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_watch_records_dealer_created_at
  ON public.watch_records (dealer_id, created_at DESC)
  WHERE dealer_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_dealer_source_identities_dealer
  ON public.dealer_source_identities (dealer_id);

ALTER TABLE public.dealers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dealer_source_identities ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.dealers FROM anon, authenticated;
REVOKE ALL ON public.dealer_source_identities FROM anon, authenticated;
GRANT ALL ON public.dealers TO service_role;
GRANT ALL ON public.dealer_source_identities TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

COMMENT ON COLUMN public.watch_records.dealer_id IS
  'Verified dealer entity. NULL means unresolved; never infer from free-form text.';
