-- Dedicated price-remediation review ledger. Proposals never overwrite the
-- shared normalization shadow row and never mutate watch_records directly.

CREATE TABLE IF NOT EXISTS public.price_remediation_review (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_record_id TEXT NOT NULL REFERENCES public.watch_records(id) ON DELETE RESTRICT,
  normalization_version TEXT NOT NULL,
  stored_price_usd NUMERIC NOT NULL CHECK (stored_price_usd > 0),
  proposed_price_usd NUMERIC NOT NULL CHECK (proposed_price_usd > 0),
  normalization_reason TEXT NOT NULL,
  evidence_line TEXT NOT NULL,
  audit_flags TEXT[] NOT NULL DEFAULT '{}',
  review_status TEXT NOT NULL DEFAULT 'PENDING'
    CHECK (review_status IN ('PENDING', 'APPROVED', 'REJECTED', 'APPLIED')),
  reviewed_by TEXT,
  reviewed_at TIMESTAMPTZ,
  applied_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (source_record_id, normalization_version),
  CHECK (stored_price_usd <> proposed_price_usd)
);

CREATE INDEX IF NOT EXISTS idx_price_remediation_review_queue
  ON public.price_remediation_review (review_status, created_at, id);

ALTER TABLE public.price_remediation_review ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.price_remediation_review FROM anon, authenticated;
GRANT ALL ON public.price_remediation_review TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.price_remediation_review_id_seq TO service_role;

COMMENT ON TABLE public.price_remediation_review IS
  'Review-only ledger for raw-evidence price corrections. Applying a row requires a separate human-approved operation with rollback evidence.';
