-- Canonical, source-backed dealer directory for QNSA.
-- This migration never rewrites immutable raw messages or staging listings.
-- Public activity is attached only through exact verified identities and an
-- explicit link ledger populated from already-released marketplace rows.

BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.dealers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text,
  display_name text,
  company_name text,
  country_code text,
  city text,
  rating numeric(3,2),
  review_count integer NOT NULL DEFAULT 0,
  whatsapp_group_count integer NOT NULL DEFAULT 0,
  avatar_url text,
  profile_summary text,
  status text NOT NULL DEFAULT 'UNVERIFIED',
  contact_consent boolean NOT NULL DEFAULT false,
  verified_at timestamptz,
  member_since text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_synced_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.dealers
  ADD COLUMN IF NOT EXISTS slug text,
  ADD COLUMN IF NOT EXISTS company_name text,
  ADD COLUMN IF NOT EXISTS country_code text,
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS rating numeric(3,2),
  ADD COLUMN IF NOT EXISTS review_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS whatsapp_group_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS avatar_url text,
  ADD COLUMN IF NOT EXISTS profile_summary text,
  ADD COLUMN IF NOT EXISTS member_since text,
  ADD COLUMN IF NOT EXISTS metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS last_synced_at timestamptz,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS idx_qnsa_dealers_slug
  ON public.dealers (lower(slug)) WHERE slug IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_qnsa_dealers_directory_order
  ON public.dealers (review_count DESC, display_name, id)
  WHERE status = 'VERIFIED';

CREATE TABLE IF NOT EXISTS public.dealer_source_identities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dealer_id uuid NOT NULL REFERENCES public.dealers(id) ON DELETE CASCADE,
  source_system text NOT NULL,
  source_identity text NOT NULL,
  identity_type text NOT NULL,
  verification_status text NOT NULL DEFAULT 'UNVERIFIED',
  first_seen_at timestamptz,
  last_seen_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_system, source_identity, identity_type)
);

CREATE OR REPLACE FUNCTION public.normalize_seller_phone_identity(p_value text)
RETURNS text LANGUAGE sql IMMUTABLE PARALLEL SAFE SET search_path = '' AS $$
  SELECT CASE
    WHEN regexp_replace(COALESCE(p_value, ''), '[^0-9]', '', 'g') ~ '^[0-9]{8,15}$'
      THEN regexp_replace(COALESCE(p_value, ''), '[^0-9]', '', 'g')
    ELSE NULL
  END;
$$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_qnsa_dealer_verified_phone
  ON public.dealer_source_identities (
    public.normalize_seller_phone_identity(source_identity)
  )
  WHERE verification_status = 'VERIFIED'
    AND upper(identity_type) IN ('PHONE', 'WHATSAPP')
    AND public.normalize_seller_phone_identity(source_identity) IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_qnsa_dealer_source_profile
  ON public.dealer_source_identities (source_system, source_identity)
  WHERE upper(identity_type) = 'SOURCE_PROFILE';

CREATE TABLE IF NOT EXISTS public.dealer_directory_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dealer_id uuid NOT NULL REFERENCES public.dealers(id) ON DELETE CASCADE,
  source_system text NOT NULL,
  source_profile_id text NOT NULL,
  captured_at timestamptz NOT NULL,
  source_rank integer,
  wts_count integer,
  wtb_count integer,
  group_count integer,
  review_count integer,
  positive_feedback_count integer,
  negative_feedback_count integer,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  imported_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_system, source_profile_id, captured_at)
);

CREATE TABLE IF NOT EXISTS public.dealer_reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dealer_id uuid NOT NULL REFERENCES public.dealers(id) ON DELETE CASCADE,
  source_system text NOT NULL,
  source_review_key text NOT NULL,
  reviewer_name text,
  review_date text,
  sentiment text,
  rating numeric(3,2),
  source_published boolean NOT NULL DEFAULT true,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (dealer_id, source_system, source_review_key)
);

CREATE TABLE IF NOT EXISTS public.dealer_group_memberships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dealer_id uuid NOT NULL REFERENCES public.dealers(id) ON DELETE CASCADE,
  source_system text NOT NULL,
  group_identity text NOT NULL,
  group_name text,
  platform text,
  membership_status text NOT NULL DEFAULT 'OBSERVED',
  source_published boolean NOT NULL DEFAULT false,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  first_seen_at timestamptz,
  last_seen_at timestamptz,
  UNIQUE (dealer_id, source_system, group_identity)
);

CREATE TABLE IF NOT EXISTS public.dealer_listing_links (
  listing_id uuid PRIMARY KEY,
  source_record_id text,
  dealer_id uuid NOT NULL REFERENCES public.dealers(id) ON DELETE RESTRICT,
  source_system text NOT NULL,
  source_identity text NOT NULL,
  link_method text NOT NULL CHECK (link_method IN ('EXACT_VERIFIED_PHONE', 'AUTHENTICATED_SUBMISSION')),
  link_status text NOT NULL DEFAULT 'APPLIED' CHECK (link_status IN ('APPLIED', 'REVOKED')),
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  linked_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_qnsa_dealer_listing_links_profile
  ON public.dealer_listing_links (dealer_id, link_status, listing_id);

ALTER TABLE public.dealers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dealer_source_identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dealer_directory_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dealer_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dealer_group_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dealer_listing_links ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.dealers, public.dealer_source_identities,
  public.dealer_directory_snapshots, public.dealer_reviews,
  public.dealer_group_memberships, public.dealer_listing_links
  FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.dealers, public.dealer_source_identities,
  public.dealer_directory_snapshots, public.dealer_reviews,
  public.dealer_group_memberships, public.dealer_listing_links TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

CREATE OR REPLACE FUNCTION public.apply_qnsa_dealer_directory_snapshot(p_records jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public AS $$
DECLARE
  v_record jsonb;
  v_dealer_id uuid;
  v_phone text;
  v_source_system text;
  v_source_profile_id text;
  v_captured_at timestamptz;
  v_profiles integer := 0;
  v_reviews integer := 0;
  v_review jsonb;
BEGIN
  IF jsonb_typeof(p_records) <> 'array' THEN
    RAISE EXCEPTION 'dealer snapshot payload must be an array';
  END IF;
  FOR v_record IN SELECT value FROM jsonb_array_elements(p_records)
  LOOP
    v_source_system := NULLIF(btrim(v_record->>'source_system'), '');
    v_source_profile_id := NULLIF(btrim(v_record->>'source_profile_id'), '');
    v_phone := public.normalize_seller_phone_identity(v_record->>'phone');
    v_captured_at := COALESCE(NULLIF(v_record->>'captured_at', '')::timestamptz, now());
    IF v_source_system IS NULL OR v_source_profile_id IS NULL THEN
      RAISE EXCEPTION 'source system and source profile id are required';
    END IF;

    v_dealer_id := NULL;
    IF v_phone IS NOT NULL THEN
      SELECT dealer_id INTO v_dealer_id
      FROM public.dealer_source_identities
      WHERE verification_status = 'VERIFIED'
        AND upper(identity_type) IN ('PHONE', 'WHATSAPP')
        AND public.normalize_seller_phone_identity(source_identity) = v_phone
      LIMIT 1;
    END IF;
    IF v_dealer_id IS NULL THEN
      SELECT dealer_id INTO v_dealer_id
      FROM public.dealer_source_identities
      WHERE source_system = v_source_system
        AND source_identity = v_source_profile_id
        AND upper(identity_type) = 'SOURCE_PROFILE'
      LIMIT 1;
    END IF;
    IF v_dealer_id IS NULL THEN
      INSERT INTO public.dealers (
        slug, display_name, company_name, country_code, city, rating,
        review_count, whatsapp_group_count, profile_summary, member_since,
        status, contact_consent, verified_at, metadata, last_synced_at
      ) VALUES (
        'dealer-' || substr(encode(extensions.digest(convert_to(v_source_system || ':' || v_source_profile_id, 'UTF8'), 'sha256'), 'hex'), 1, 20),
        NULLIF(btrim(v_record->>'display_name'), ''), NULLIF(btrim(v_record->>'company_name'), ''),
        NULLIF(btrim(v_record->>'country_code'), ''), NULLIF(btrim(v_record->>'city'), ''),
        CASE WHEN (v_record->>'rating') ~ '^([0-4](\.\d+)?|5(\.0+)?)$' THEN (v_record->>'rating')::numeric ELSE NULL END,
        GREATEST(COALESCE((v_record->>'review_count')::integer, 0), 0),
        GREATEST(COALESCE((v_record->>'group_count')::integer, 0), 0),
        NULLIF(btrim(v_record->>'profile_summary'), ''), NULLIF(btrim(v_record->>'member_since'), ''),
        'VERIFIED', COALESCE((v_record->>'contact_consent')::boolean, false), v_captured_at,
        jsonb_build_object('trust_status', v_record->>'trust_status'), v_captured_at
      ) RETURNING id INTO v_dealer_id;
    ELSE
      UPDATE public.dealers SET
        display_name = COALESCE(NULLIF(btrim(v_record->>'display_name'), ''), display_name),
        company_name = COALESCE(NULLIF(btrim(v_record->>'company_name'), ''), company_name),
        country_code = COALESCE(NULLIF(btrim(v_record->>'country_code'), ''), country_code),
        city = COALESCE(NULLIF(btrim(v_record->>'city'), ''), city),
        review_count = GREATEST(review_count, COALESCE((v_record->>'review_count')::integer, 0)),
        whatsapp_group_count = GREATEST(whatsapp_group_count, COALESCE((v_record->>'group_count')::integer, 0)),
        profile_summary = COALESCE(NULLIF(btrim(v_record->>'profile_summary'), ''), profile_summary),
        member_since = COALESCE(NULLIF(btrim(v_record->>'member_since'), ''), member_since),
        status = 'VERIFIED', last_synced_at = v_captured_at, updated_at = now()
      WHERE id = v_dealer_id;
    END IF;

    INSERT INTO public.dealer_source_identities (
      dealer_id, source_system, source_identity, identity_type,
      verification_status, first_seen_at, last_seen_at, metadata
    ) VALUES (
      v_dealer_id, v_source_system, v_source_profile_id, 'SOURCE_PROFILE',
      'VERIFIED', v_captured_at, v_captured_at, '{}'::jsonb
    ) ON CONFLICT (source_system, source_identity, identity_type) DO UPDATE SET
      dealer_id = EXCLUDED.dealer_id, verification_status = 'VERIFIED',
      last_seen_at = EXCLUDED.last_seen_at;

    IF v_phone IS NOT NULL THEN
      INSERT INTO public.dealer_source_identities (
        dealer_id, source_system, source_identity, identity_type,
        verification_status, first_seen_at, last_seen_at, metadata
      ) VALUES (
        v_dealer_id, 'GLOBAL_PHONE', v_phone, 'PHONE', 'VERIFIED',
        v_captured_at, v_captured_at, jsonb_build_object('source_system', v_source_system)
      ) ON CONFLICT (source_system, source_identity, identity_type) DO UPDATE SET
        dealer_id = EXCLUDED.dealer_id, verification_status = 'VERIFIED',
        last_seen_at = EXCLUDED.last_seen_at;
    END IF;

    INSERT INTO public.dealer_directory_snapshots (
      dealer_id, source_system, source_profile_id, captured_at, source_rank,
      wts_count, wtb_count, group_count, review_count,
      positive_feedback_count, negative_feedback_count, evidence
    ) VALUES (
      v_dealer_id, v_source_system, v_source_profile_id, v_captured_at,
      NULLIF(v_record->>'source_rank', '')::integer,
      NULLIF(v_record->>'wts_count', '')::integer, NULLIF(v_record->>'wtb_count', '')::integer,
      NULLIF(v_record->>'group_count', '')::integer, NULLIF(v_record->>'review_count', '')::integer,
      NULLIF(v_record->>'positive_feedback_count', '')::integer,
      NULLIF(v_record->>'negative_feedback_count', '')::integer,
      COALESCE(v_record->'evidence', '{}'::jsonb)
    ) ON CONFLICT (source_system, source_profile_id, captured_at) DO UPDATE SET
      dealer_id = EXCLUDED.dealer_id, source_rank = EXCLUDED.source_rank,
      wts_count = EXCLUDED.wts_count, wtb_count = EXCLUDED.wtb_count,
      group_count = EXCLUDED.group_count, review_count = EXCLUDED.review_count,
      positive_feedback_count = EXCLUDED.positive_feedback_count,
      negative_feedback_count = EXCLUDED.negative_feedback_count,
      evidence = EXCLUDED.evidence;

    FOR v_review IN SELECT value FROM jsonb_array_elements(COALESCE(v_record->'reviews', '[]'::jsonb))
    LOOP
      INSERT INTO public.dealer_reviews (
        dealer_id, source_system, source_review_key, reviewer_name,
        review_date, sentiment, rating, source_published, evidence
      ) VALUES (
        v_dealer_id, v_source_system, v_review->>'key',
        NULLIF(btrim(v_review->>'reviewer'), ''), NULLIF(btrim(v_review->>'date'), ''),
        NULLIF(btrim(v_review->>'sentiment'), ''),
        CASE WHEN (v_review->>'rating') ~ '^([0-4](\.\d+)?|5(\.0+)?)$' THEN (v_review->>'rating')::numeric ELSE NULL END,
        true, COALESCE(v_review->'evidence', '{}'::jsonb)
      ) ON CONFLICT (dealer_id, source_system, source_review_key) DO NOTHING;
      v_reviews := v_reviews + 1;
    END LOOP;
    v_profiles := v_profiles + 1;
  END LOOP;
  RETURN jsonb_build_object('profiles_processed', v_profiles, 'reviews_processed', v_reviews);
END;
$$;

CREATE OR REPLACE FUNCTION public.apply_qnsa_dealer_listing_links(p_records jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public AS $$
DECLARE
  v_record jsonb;
  v_phone text;
  v_dealer_id uuid;
  v_matches integer;
  v_applied integer := 0;
  v_unresolved integer := 0;
BEGIN
  IF jsonb_typeof(p_records) <> 'array' THEN RAISE EXCEPTION 'listing link payload must be an array'; END IF;
  FOR v_record IN SELECT value FROM jsonb_array_elements(p_records)
  LOOP
    v_phone := public.normalize_seller_phone_identity(v_record->>'seller_phone');
    SELECT count(DISTINCT dealer_id), min(dealer_id::text)::uuid
      INTO v_matches, v_dealer_id
    FROM public.dealer_source_identities
    WHERE verification_status = 'VERIFIED'
      AND upper(identity_type) IN ('PHONE', 'WHATSAPP')
      AND public.normalize_seller_phone_identity(source_identity) = v_phone;
    IF v_phone IS NULL OR v_matches <> 1 THEN
      v_unresolved := v_unresolved + 1;
      CONTINUE;
    END IF;
    INSERT INTO public.dealer_listing_links (
      listing_id, source_record_id, dealer_id, source_system, source_identity,
      link_method, link_status, evidence, updated_at
    ) VALUES (
      (v_record->>'listing_id')::uuid, NULLIF(v_record->>'source_record_id', ''),
      v_dealer_id, 'PUBLIC_MARKET_RELEASE', v_phone,
      'EXACT_VERIFIED_PHONE', 'APPLIED',
      jsonb_build_object('seller_name', v_record->>'seller_name', 'captured_at', v_record->>'captured_at'), now()
    ) ON CONFLICT (listing_id) DO UPDATE SET
      dealer_id = EXCLUDED.dealer_id, source_record_id = EXCLUDED.source_record_id,
      source_identity = EXCLUDED.source_identity, link_status = 'APPLIED',
      evidence = EXCLUDED.evidence, updated_at = now();
    v_applied := v_applied + 1;
  END LOOP;
  RETURN jsonb_build_object('applied', v_applied, 'unresolved', v_unresolved);
END;
$$;

CREATE OR REPLACE FUNCTION public.qnsa_dealer_directory_page(
  p_search text DEFAULT NULL, p_limit integer DEFAULT 24, p_offset integer DEFAULT 0
) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, public AS $$
  WITH activity AS (
    SELECT dealer_id,
      count(*) FILTER (WHERE upper(COALESCE(l.listing_type, l.intent, '')) = 'WTS') wts_count,
      count(*) FILTER (WHERE upper(COALESCE(l.listing_type, l.intent, '')) = 'WTB') wtb_count,
      min(l.created_at) first_post, max(l.created_at) latest_post
    FROM public.dealer_listing_links link
    JOIN staging.listings l ON l.id = link.listing_id
    WHERE link.link_status = 'APPLIED'
    GROUP BY dealer_id
  ), filtered AS (
    SELECT d.*, COALESCE(a.wts_count, 0) wts_count, COALESCE(a.wtb_count, 0) wtb_count,
      a.first_post, a.latest_post,
      count(*) OVER () total_count
    FROM public.dealers d LEFT JOIN activity a ON a.dealer_id = d.id
    WHERE d.status = 'VERIFIED' AND (
      NULLIF(btrim(p_search), '') IS NULL
      OR d.display_name ILIKE '%' || btrim(p_search) || '%'
      OR d.company_name ILIKE '%' || btrim(p_search) || '%'
      OR EXISTS (
        SELECT 1 FROM public.dealer_source_identities i
        WHERE i.dealer_id = d.id AND i.verification_status = 'VERIFIED'
          AND public.normalize_seller_phone_identity(i.source_identity)
              LIKE '%' || public.normalize_seller_phone_identity(p_search) || '%'
      )
    )
    ORDER BY d.review_count DESC, d.display_name, d.id
    LIMIT LEAST(GREATEST(COALESCE(p_limit, 24), 1), 100)
    OFFSET GREATEST(COALESCE(p_offset, 0), 0)
  )
  SELECT jsonb_build_object(
    'total', COALESCE(max(total_count), 0),
    'dealers', COALESCE(jsonb_agg(jsonb_build_object(
      'id', id, 'slug', slug, 'display_name', display_name,
      'company_name', company_name, 'country_code', country_code, 'city', city,
      'rating', rating, 'review_count', review_count,
      'whatsapp_group_count', whatsapp_group_count, 'member_since', member_since,
      'verified_at', verified_at,
      'stats', jsonb_build_object('wts_posts', wts_count, 'wtb_posts', wtb_count,
        'first_post_at', first_post, 'last_post_at', latest_post)
    ) ORDER BY review_count DESC, display_name, id), '[]'::jsonb)
  ) FROM filtered;
$$;

CREATE OR REPLACE FUNCTION public.qnsa_dealer_profile(
  p_identity text, p_limit integer DEFAULT 50, p_offset integer DEFAULT 0
) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, public, staging AS $$
  WITH target AS (
    SELECT d.* FROM public.dealers d
    WHERE d.status = 'VERIFIED'
      AND (d.id::text = p_identity OR lower(d.slug) = lower(p_identity))
    LIMIT 1
  ), linked AS (
    SELECT l.*, link.dealer_id, count(*) OVER () total_count
    FROM public.dealer_listing_links link
    JOIN staging.listings l ON l.id = link.listing_id
    JOIN target d ON d.id = link.dealer_id
    WHERE link.link_status = 'APPLIED'
    ORDER BY l.created_at DESC NULLS LAST, l.id DESC
  ), totals AS (
    SELECT count(*) FILTER (WHERE upper(COALESCE(listing_type, intent, '')) = 'WTS') wts_count,
      count(*) FILTER (WHERE upper(COALESCE(listing_type, intent, '')) = 'WTB') wtb_count,
      min(created_at) first_post, max(created_at) latest_post
    FROM linked
  ), page AS (
    SELECT * FROM linked
    LIMIT LEAST(GREATEST(COALESCE(p_limit, 50), 1), 100)
    OFFSET GREATEST(COALESCE(p_offset, 0), 0)
  )
  SELECT jsonb_build_object(
    'dealer', (SELECT jsonb_build_object(
      'id', d.id, 'slug', d.slug, 'display_name', d.display_name,
      'company_name', d.company_name, 'country_code', d.country_code, 'city', d.city,
      'rating', d.rating, 'review_count', d.review_count,
      'whatsapp_group_count', d.whatsapp_group_count, 'member_since', d.member_since,
      'profile_summary', d.profile_summary, 'verified_at', d.verified_at,
      'verified_phone', CASE WHEN d.contact_consent THEN (
        SELECT '+' || public.normalize_seller_phone_identity(i.source_identity)
        FROM public.dealer_source_identities i WHERE i.dealer_id = d.id
          AND i.verification_status = 'VERIFIED' AND upper(i.identity_type) IN ('PHONE','WHATSAPP') LIMIT 1
      ) ELSE NULL END
    ) FROM target d),
    'stats', (SELECT jsonb_build_object('wts_count', wts_count, 'wtb_count', wtb_count,
      'group_count', (SELECT whatsapp_group_count FROM target),
      'first_post', first_post, 'latest_post', latest_post,
      'current_counts_are_dynamic', true) FROM totals),
    'listing_total', (SELECT count(*) FROM linked),
    'listings', COALESCE((SELECT jsonb_agg(jsonb_build_object(
      'id', p.id, 'brand', p.brand_normalized, 'model', p.model_normalized,
      'reference', p.reference_normalized, 'dial_color', p.dial_color_normalized,
      'condition', p.condition_normalized,
      'price_usd', CASE WHEN p.price_usd > 0 THEN p.price_usd ELSE NULL END,
      'price_raw', CASE WHEN p.price_normalized > 0 THEN p.price_normalized ELSE NULL END,
      'currency', p.currency_normalized,
      'listing_type', upper(COALESCE(p.listing_type, p.intent)),
      'listing_date', p.created_at, 'raw_message', p.raw_message_text,
      'image_url', CASE WHEN p.public_image_eligible AND p.image_url ~* '^https?://' THEN p.image_url ELSE NULL END,
      'seller_name', COALESCE(NULLIF(btrim(p.user_name), ''), NULLIF(btrim(p.from_name), '')),
      'location', p.location
    ) ORDER BY p.created_at DESC NULLS LAST, p.id DESC) FROM page p), '[]'::jsonb),
    'reviews', COALESCE((SELECT jsonb_agg(jsonb_build_object(
      'date', r.review_date, 'reviewer', r.reviewer_name,
      'sentiment', r.sentiment, 'rating', r.rating
    ) ORDER BY r.id DESC) FROM public.dealer_reviews r JOIN target d ON d.id = r.dealer_id
      WHERE r.source_published), '[]'::jsonb),
    'groups', COALESCE((SELECT jsonb_agg(jsonb_build_object(
      'name', g.group_name, 'platform', g.platform, 'membership_status', g.membership_status
    ) ORDER BY g.group_name) FROM public.dealer_group_memberships g JOIN target d ON d.id = g.dealer_id
      WHERE g.source_published), '[]'::jsonb)
  );
$$;

REVOKE ALL ON FUNCTION public.apply_qnsa_dealer_directory_snapshot(jsonb),
  public.apply_qnsa_dealer_listing_links(jsonb),
  public.qnsa_dealer_directory_page(text, integer, integer),
  public.qnsa_dealer_profile(text, integer, integer)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.apply_qnsa_dealer_directory_snapshot(jsonb),
  public.apply_qnsa_dealer_listing_links(jsonb),
  public.qnsa_dealer_directory_page(text, integer, integer),
  public.qnsa_dealer_profile(text, integer, integer)
  TO service_role;

COMMIT;
