-- Private, exact-evidence seller/dealer review. Approval is the only path in
-- this migration that may attach a verified dealer to a listing.

BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';

CREATE OR REPLACE FUNCTION public.normalize_seller_phone_identity(p_value TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
SET search_path = ''
AS $$
  SELECT CASE
    WHEN regexp_replace(COALESCE(p_value, ''), '[^0-9]', '', 'g') ~ '^[0-9]{8,15}$'
      THEN regexp_replace(COALESCE(p_value, ''), '[^0-9]', '', 'g')
    ELSE NULL
  END;
$$;

REVOKE ALL ON FUNCTION public.normalize_seller_phone_identity(TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.normalize_seller_phone_identity(TEXT)
  TO service_role;

CREATE INDEX IF NOT EXISTS idx_dealer_source_identity_exact_phone
  ON public.dealer_source_identities (
    source_system,
    public.normalize_seller_phone_identity(source_identity)
  )
  WHERE verification_status = 'VERIFIED'
    AND upper(trim(identity_type)) = 'PHONE';

CREATE INDEX IF NOT EXISTS idx_seller_lineage_exact_phone_review
  ON public.seller_listing_lineage_staging (
    source_system,
    public.normalize_seller_phone_identity(source_identity),
    imported_at DESC
  )
  WHERE match_status = 'MATCH_READY';

CREATE TABLE IF NOT EXISTS public.seller_lineage_review_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lineage_id BIGINT NOT NULL
    REFERENCES public.seller_listing_lineage_staging(id) ON DELETE RESTRICT,
  source_record_id TEXT NOT NULL
    REFERENCES public.watch_records(id) ON DELETE RESTRICT,
  dealer_id UUID REFERENCES public.dealers(id) ON DELETE RESTRICT,
  decision TEXT NOT NULL CHECK (decision IN ('APPROVE', 'REJECT')),
  operator_id TEXT NOT NULL CHECK (length(trim(operator_id)) > 0),
  reason TEXT NOT NULL CHECK (length(trim(reason)) >= 12),
  evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_seller_lineage_review_events_lineage
  ON public.seller_lineage_review_events (lineage_id, created_at DESC);

ALTER TABLE public.seller_lineage_review_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.seller_lineage_review_events FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.seller_lineage_review_events TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

CREATE OR REPLACE FUNCTION public.prevent_seller_lineage_review_event_mutation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  RAISE EXCEPTION 'seller_lineage_review_events is append-only';
END;
$$;

REVOKE ALL ON FUNCTION public.prevent_seller_lineage_review_event_mutation()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS seller_lineage_review_events_append_only
  ON public.seller_lineage_review_events;
CREATE TRIGGER seller_lineage_review_events_append_only
  BEFORE UPDATE OR DELETE ON public.seller_lineage_review_events
  FOR EACH ROW EXECUTE FUNCTION public.prevent_seller_lineage_review_event_mutation();

CREATE OR REPLACE VIEW public.seller_lineage_review_queue
WITH (security_invoker = true)
AS
WITH exact_candidates AS (
  SELECT
    s.id AS lineage_id,
    s.source_record_id,
    w.id AS record_id,
    w.raw_message,
    s.observed_name,
    s.source_identity,
    s.source_system,
    s.source_listing_type,
    s.source_posted_at,
    s.front_image,
    s.match_status,
    s.match_evidence,
    s.imported_at,
    d.id AS proposed_dealer_id,
    d.display_name AS proposed_dealer_display_name,
    d.company_name AS proposed_dealer_company_name,
    d.status AS proposed_dealer_status,
    w.dealer_id AS existing_dealer_id,
    count(*) OVER (PARTITION BY s.id) AS exact_candidate_count
  FROM public.seller_listing_lineage_staging s
  JOIN public.watch_records w
    ON w.id = s.source_record_id
  JOIN public.dealer_source_identities identity_row
    ON identity_row.source_system = s.source_system
   AND upper(trim(identity_row.identity_type)) = 'PHONE'
   AND identity_row.verification_status = 'VERIFIED'
   AND public.normalize_seller_phone_identity(identity_row.source_identity)
       = public.normalize_seller_phone_identity(s.source_identity)
  JOIN public.dealers d
    ON d.id = identity_row.dealer_id
   AND d.status = 'VERIFIED'
  WHERE s.match_status = 'MATCH_READY'
    AND upper(trim(s.identity_type)) = 'PHONE'
    AND public.normalize_seller_phone_identity(s.source_identity) IS NOT NULL
    AND s.match_evidence->'exact_raw_message_sha1' = 'true'::jsonb
    AND s.match_evidence->'exact_wall_clock_second' = 'true'::jsonb
    AND s.match_evidence->'unique_phone_identity' = 'true'::jsonb
    AND s.match_evidence->'intent_agreement' = 'true'::jsonb
    AND s.title_sha1 = encode(
      extensions.digest(convert_to(COALESCE(w.raw_message, ''), 'UTF8'), 'sha1'),
      'hex'
    )
    AND CASE
      WHEN upper(trim(COALESCE(s.source_listing_type, ''))) IN ('SALE', 'WTS')
        THEN upper(trim(COALESCE(w.listing_type, ''))) = 'WTS'
      WHEN upper(trim(COALESCE(s.source_listing_type, ''))) IN ('SEARCH', 'WTB', 'NTQ')
        THEN upper(trim(COALESCE(w.listing_type, ''))) IN ('WTB', 'NTQ')
      ELSE false
    END
)
SELECT
  lineage_id,
  source_record_id,
  record_id,
  raw_message,
  observed_name,
  source_identity,
  source_system,
  source_listing_type,
  source_posted_at,
  front_image,
  match_status,
  match_evidence,
  imported_at,
  proposed_dealer_id,
  proposed_dealer_display_name,
  proposed_dealer_company_name,
  proposed_dealer_status
FROM exact_candidates
WHERE exact_candidate_count = 1
  AND (existing_dealer_id IS NULL OR existing_dealer_id = proposed_dealer_id);

REVOKE ALL ON public.seller_lineage_review_queue
  FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.seller_lineage_review_queue TO service_role;

CREATE OR REPLACE FUNCTION public.apply_seller_lineage_review_decision(
  p_lineage_id BIGINT,
  p_record_id TEXT,
  p_dealer_id UUID,
  p_decision TEXT,
  p_operator_id TEXT,
  p_reason TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_decision TEXT := upper(trim(COALESCE(p_decision, '')));
  v_operator_id TEXT := trim(COALESCE(p_operator_id, ''));
  v_reason TEXT := trim(COALESCE(p_reason, ''));
  v_staging public.seller_listing_lineage_staging;
  v_record public.watch_records;
  v_dealer public.dealers;
  v_identity_count INTEGER;
  v_existing_decision TEXT;
BEGIN
  IF v_decision NOT IN ('APPROVE', 'REJECT') THEN
    RAISE EXCEPTION 'Seller lineage decision must be APPROVE or REJECT';
  END IF;
  IF v_operator_id = '' THEN
    RAISE EXCEPTION 'A named operator is required';
  END IF;
  IF length(v_reason) < 12 THEN
    RAISE EXCEPTION 'Review reason must contain at least 12 characters';
  END IF;
  IF v_decision = 'APPROVE' AND p_dealer_id IS NULL THEN
    RAISE EXCEPTION 'Approval requires a verified dealer';
  END IF;

  SELECT *
  INTO v_staging
  FROM public.seller_listing_lineage_staging
  WHERE id = p_lineage_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Seller lineage row not found';
  END IF;

  IF NULLIF(trim(COALESCE(p_record_id, '')), '') IS NULL
    OR v_staging.source_record_id IS DISTINCT FROM p_record_id
  THEN
    RAISE EXCEPTION 'Staging source_record_id does not exactly match the requested listing record';
  END IF;

  SELECT *
  INTO v_record
  FROM public.watch_records
  WHERE id = p_record_id
  FOR UPDATE;

  IF NOT FOUND OR v_record.id IS DISTINCT FROM v_staging.source_record_id THEN
    RAISE EXCEPTION 'Staging source_record_id does not exactly match a listing record';
  END IF;

  SELECT decision
  INTO v_existing_decision
  FROM public.seller_lineage_review_events
  WHERE lineage_id = p_lineage_id
  ORDER BY id DESC
  LIMIT 1;

  IF v_existing_decision IS NOT NULL THEN
    IF v_existing_decision <> v_decision THEN
      RAISE EXCEPTION 'Seller lineage row already has a conflicting final decision';
    END IF;
    IF v_decision = 'APPROVE'
      AND (
        v_staging.match_status <> 'APPLIED'
        OR v_staging.matched_dealer_id IS DISTINCT FROM p_dealer_id
        OR v_record.dealer_id IS DISTINCT FROM p_dealer_id
      )
    THEN
      RAISE EXCEPTION 'Existing approval state conflicts with the requested dealer';
    END IF;
    IF v_decision = 'REJECT'
      AND (
        v_staging.match_status <> 'REJECTED'
        OR v_staging.matched_dealer_id IS NOT NULL
      )
    THEN
      RAISE EXCEPTION 'Existing rejection state is inconsistent';
    END IF;

    RETURN jsonb_build_object(
      'lineage_id', p_lineage_id,
      'source_record_id', v_staging.source_record_id,
      'dealer_id', v_staging.matched_dealer_id,
      'decision', v_decision,
      'status', v_staging.match_status,
      'idempotent', true,
      'contact_published', false
    );
  END IF;

  IF v_staging.match_status <> 'MATCH_READY' THEN
    RAISE EXCEPTION 'Seller lineage row is not MATCH_READY';
  END IF;

  IF v_decision = 'REJECT' THEN
    IF v_staging.matched_dealer_id IS NOT NULL THEN
      RAISE EXCEPTION 'Cannot reject a lineage row that already has a dealer attachment';
    END IF;

    INSERT INTO public.seller_lineage_review_events (
      lineage_id,
      source_record_id,
      dealer_id,
      decision,
      operator_id,
      reason,
      evidence
    ) VALUES (
      v_staging.id,
      v_staging.source_record_id,
      NULL,
      v_decision,
      v_operator_id,
      v_reason,
      jsonb_build_object(
        'match_status_before', v_staging.match_status,
        'match_evidence', v_staging.match_evidence,
        'dealer_attached', false
      )
    );

    UPDATE public.seller_listing_lineage_staging
    SET
      match_status = 'REJECTED',
      matched_dealer_id = NULL,
      updated_at = now()
    WHERE id = v_staging.id;

    RETURN jsonb_build_object(
      'lineage_id', v_staging.id,
      'source_record_id', v_staging.source_record_id,
      'dealer_id', NULL,
      'decision', v_decision,
      'status', 'REJECTED',
      'idempotent', false,
      'contact_published', false
    );
  END IF;

  IF v_staging.match_evidence->'exact_raw_message_sha1' IS DISTINCT FROM 'true'::jsonb
    OR v_staging.match_evidence->'exact_wall_clock_second' IS DISTINCT FROM 'true'::jsonb
    OR v_staging.match_evidence->'unique_phone_identity' IS DISTINCT FROM 'true'::jsonb
    OR v_staging.match_evidence->'intent_agreement' IS DISTINCT FROM 'true'::jsonb
  THEN
    RAISE EXCEPTION 'Exact seller lineage evidence gate failed';
  END IF;

  IF v_staging.title_sha1 IS DISTINCT FROM encode(
    extensions.digest(convert_to(COALESCE(v_record.raw_message, ''), 'UTF8'), 'sha1'),
    'hex'
  ) THEN
    RAISE EXCEPTION 'Stored raw message does not match the staged SHA-1 evidence';
  END IF;

  IF public.normalize_seller_phone_identity(v_staging.source_identity) IS NULL THEN
    RAISE EXCEPTION 'Staged phone identity is invalid';
  END IF;

  IF upper(trim(COALESCE(v_staging.identity_type, ''))) <> 'PHONE' THEN
    RAISE EXCEPTION 'Staged identity type is not PHONE';
  END IF;

  IF (CASE
    WHEN upper(trim(COALESCE(v_staging.source_listing_type, ''))) IN ('SALE', 'WTS')
      THEN upper(trim(COALESCE(v_record.listing_type, ''))) = 'WTS'
    WHEN upper(trim(COALESCE(v_staging.source_listing_type, ''))) IN ('SEARCH', 'WTB', 'NTQ')
      THEN upper(trim(COALESCE(v_record.listing_type, ''))) IN ('WTB', 'NTQ')
    ELSE false
  END) IS NOT TRUE THEN
    RAISE EXCEPTION 'Staged source intent does not match the listing intent';
  END IF;

  SELECT *
  INTO v_dealer
  FROM public.dealers
  WHERE id = p_dealer_id
    AND status = 'VERIFIED'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Dealer is not VERIFIED';
  END IF;

  SELECT count(*)
  INTO v_identity_count
  FROM public.dealer_source_identities identity_row
  JOIN public.dealers candidate_dealer
    ON candidate_dealer.id = identity_row.dealer_id
   AND candidate_dealer.status = 'VERIFIED'
  WHERE identity_row.source_system = v_staging.source_system
    AND upper(trim(identity_row.identity_type)) = 'PHONE'
    AND identity_row.verification_status = 'VERIFIED'
    AND public.normalize_seller_phone_identity(identity_row.source_identity)
        = public.normalize_seller_phone_identity(v_staging.source_identity);

  IF v_identity_count <> 1 THEN
    RAISE EXCEPTION 'Verified dealer phone identity is missing or ambiguous';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.dealer_source_identities identity_row
    WHERE identity_row.dealer_id = p_dealer_id
      AND identity_row.source_system = v_staging.source_system
      AND upper(trim(identity_row.identity_type)) = 'PHONE'
      AND identity_row.verification_status = 'VERIFIED'
      AND public.normalize_seller_phone_identity(identity_row.source_identity)
          = public.normalize_seller_phone_identity(v_staging.source_identity)
  ) THEN
    RAISE EXCEPTION 'Requested dealer does not own the exact verified source identity';
  END IF;

  IF v_staging.matched_dealer_id IS NOT NULL
    AND v_staging.matched_dealer_id IS DISTINCT FROM p_dealer_id
  THEN
    RAISE EXCEPTION 'Staged dealer attachment conflicts with the requested dealer';
  END IF;

  IF v_record.dealer_id IS NOT NULL
    AND v_record.dealer_id IS DISTINCT FROM p_dealer_id
  THEN
    RAISE EXCEPTION 'Listing already belongs to a different dealer';
  END IF;

  INSERT INTO public.seller_lineage_review_events (
    lineage_id,
    source_record_id,
    dealer_id,
    decision,
    operator_id,
    reason,
    evidence
  ) VALUES (
    v_staging.id,
    v_staging.source_record_id,
    p_dealer_id,
    v_decision,
    v_operator_id,
    v_reason,
    jsonb_build_object(
      'match_status_before', v_staging.match_status,
      'match_evidence', v_staging.match_evidence,
      'source_system', v_staging.source_system,
      'identity_type', 'PHONE',
      'normalized_phone_sha256',
        encode(
          extensions.digest(
            convert_to(public.normalize_seller_phone_identity(v_staging.source_identity), 'UTF8'),
            'sha256'
          ),
          'hex'
        ),
      'dealer_status', v_dealer.status,
      'contact_consent', v_dealer.contact_consent
    )
  );

  UPDATE public.seller_listing_lineage_staging
  SET
    matched_dealer_id = p_dealer_id,
    match_status = 'APPLIED',
    updated_at = now()
  WHERE id = v_staging.id;

  UPDATE public.watch_records
  SET dealer_id = p_dealer_id
  WHERE id = v_staging.source_record_id
    AND (dealer_id IS NULL OR dealer_id = p_dealer_id);

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Listing dealer attachment changed concurrently';
  END IF;

  RETURN jsonb_build_object(
    'lineage_id', v_staging.id,
    'source_record_id', v_staging.source_record_id,
    'dealer_id', p_dealer_id,
    'decision', v_decision,
    'status', 'APPLIED',
    'idempotent', false,
    'contact_published', false,
    'contact_access_requires_listing_contact_gate', true
  );
END;
$$;

REVOKE ALL ON FUNCTION public.apply_seller_lineage_review_decision(
  BIGINT, TEXT, UUID, TEXT, TEXT, TEXT
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.apply_seller_lineage_review_decision(
  BIGINT, TEXT, UUID, TEXT, TEXT, TEXT
) TO service_role;

NOTIFY pgrst, 'reload schema';
COMMIT;
