-- Private, review-first seller lineage. This table never publishes a phone,
-- verifies a dealer, or changes a customer listing by itself.

CREATE TABLE IF NOT EXISTS public.seller_listing_lineage_staging (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system TEXT NOT NULL,
  source_record_id TEXT NOT NULL,
  seller_listing_id TEXT NOT NULL,
  title_sha1 TEXT NOT NULL CHECK (title_sha1 ~ '^[a-f0-9]{40}$'),
  source_identity TEXT NOT NULL,
  identity_type TEXT NOT NULL DEFAULT 'PHONE' CHECK (identity_type = 'PHONE'),
  observed_name TEXT,
  origin TEXT,
  source_listing_type TEXT,
  source_posted_at TIMESTAMPTZ,
  source_posted_at_raw TEXT,
  front_image TEXT,
  match_status TEXT NOT NULL DEFAULT 'MATCH_READY'
    CHECK (match_status IN ('MATCH_READY', 'REVIEW_REQUIRED', 'REJECTED', 'APPLIED')),
  match_evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
  matched_dealer_id UUID REFERENCES public.dealers(id) ON DELETE SET NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (source_system, source_record_id, seller_listing_id)
);

CREATE INDEX IF NOT EXISTS idx_seller_lineage_staging_status
  ON public.seller_listing_lineage_staging (match_status, imported_at DESC);
CREATE INDEX IF NOT EXISTS idx_seller_lineage_staging_source_record
  ON public.seller_listing_lineage_staging (source_record_id);
CREATE INDEX IF NOT EXISTS idx_seller_lineage_staging_identity
  ON public.seller_listing_lineage_staging (source_identity)
  WHERE match_status IN ('MATCH_READY', 'REVIEW_REQUIRED');

ALTER TABLE public.seller_listing_lineage_staging ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.seller_listing_lineage_staging FROM anon, authenticated;
GRANT ALL ON public.seller_listing_lineage_staging TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

COMMENT ON TABLE public.seller_listing_lineage_staging IS
  'Private evidence linking unbundled source records to source listing identities. Requires review before dealer linkage; never customer-readable.';
