-- Private child-level lineage inherited from an exact parent-message match.
-- This table is evidence for review only. It cannot publish contact details,
-- approve listings, attach images, or suppress duplicates.

CREATE TABLE IF NOT EXISTS public.seller_child_lineage_staging (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  child_id TEXT NOT NULL UNIQUE,
  source_child_id TEXT,
  source_system TEXT NOT NULL,
  source_record_id TEXT NOT NULL,
  seller_listing_id TEXT NOT NULL,
  seller_identity_pseudonym TEXT NOT NULL
    CHECK (seller_identity_pseudonym ~ '^[a-f0-9]{20}$'),
  source_posted_at TIMESTAMPTZ NOT NULL,
  source_posted_at_raw TEXT,
  child_intent TEXT CHECK (child_intent IN ('WTS', 'WTB')),
  source_parent_intent TEXT CHECK (source_parent_intent IN ('WTS', 'WTB')),
  activity_count_eligible BOOLEAN NOT NULL DEFAULT false,
  dealer_id UUID REFERENCES public.dealers(id) ON DELETE SET NULL,
  dealer_verification_status TEXT NOT NULL DEFAULT 'REQUIRES_VERIFIED_DEALER_MATCH'
    CHECK (dealer_verification_status IN ('REQUIRES_VERIFIED_DEALER_MATCH', 'VERIFIED_DEALER_MATCH')),
  public_contact_eligible BOOLEAN NOT NULL DEFAULT false
    CHECK (public_contact_eligible IS false),
  parent_front_image TEXT,
  image_lineage_status TEXT NOT NULL DEFAULT 'NO_PARENT_IMAGE'
    CHECK (image_lineage_status IN ('NO_PARENT_IMAGE', 'PARENT_EVIDENCE_ONLY', 'CHILD_IMAGE_VERIFIED')),
  child_image_publication_eligible BOOLEAN NOT NULL DEFAULT false
    CHECK (child_image_publication_eligible IS false),
  review_status TEXT NOT NULL DEFAULT 'PENDING'
    CHECK (review_status IN ('PENDING', 'REVIEWED', 'REJECTED')),
  review_reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
  evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
  listing_fingerprint TEXT NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT seller_child_lineage_parent_fk
    FOREIGN KEY (source_system, source_record_id, seller_listing_id)
    REFERENCES public.seller_listing_lineage_staging
      (source_system, source_record_id, seller_listing_id)
    ON DELETE RESTRICT,
  CONSTRAINT seller_child_lineage_intent_gate
    CHECK (
      activity_count_eligible IS false
      OR (child_intent IS NOT NULL AND child_intent = source_parent_intent)
    ),
  CONSTRAINT seller_child_lineage_image_evidence_gate
    CHECK (
      image_lineage_status <> 'CHILD_IMAGE_VERIFIED'
      OR parent_front_image IS NOT NULL
    )
);

CREATE INDEX IF NOT EXISTS idx_seller_child_lineage_review
  ON public.seller_child_lineage_staging (review_status, imported_at DESC);
CREATE INDEX IF NOT EXISTS idx_seller_child_lineage_parent
  ON public.seller_child_lineage_staging (source_system, source_record_id);
CREATE INDEX IF NOT EXISTS idx_seller_child_lineage_seller_config
  ON public.seller_child_lineage_staging
    (seller_identity_pseudonym, listing_fingerprint, source_posted_at DESC);

ALTER TABLE public.seller_child_lineage_staging ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.seller_child_lineage_staging FROM anon, authenticated;
GRANT ALL ON public.seller_child_lineage_staging TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.seller_child_lineage_staging_id_seq TO service_role;

COMMENT ON TABLE public.seller_child_lineage_staging IS
  'Private review evidence connecting normalized children to exact parent seller/date lineage. Never customer-readable and never a publication authority.';

NOTIFY pgrst, 'reload schema';
