-- Versioned live-ingestion lineage. Raw source evidence is immutable; parsed
-- prices and assertions remain linked to the generated watch record.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.raw_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  external_message_id TEXT,
  sender_phone TEXT,
  group_id TEXT,
  source_platform TEXT NOT NULL,
  received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  raw_text TEXT NOT NULL,
  raw_payload JSONB,
  media_count INTEGER NOT NULL DEFAULT 0,
  processing_status TEXT NOT NULL DEFAULT 'PENDING',
  parser_version TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_raw_messages_external_identity
  ON public.raw_messages (source_platform, external_message_id)
  WHERE external_message_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.listing_prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id TEXT NOT NULL REFERENCES public.watch_records(id) ON DELETE CASCADE,
  price_type TEXT NOT NULL,
  amount_original NUMERIC,
  currency_original TEXT,
  amount_usd NUMERIC,
  is_primary BOOLEAN NOT NULL DEFAULT false,
  raw_price_text TEXT,
  confidence INTEGER,
  currency_evidence TEXT,
  discount_percent NUMERIC,
  retail_price NUMERIC,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_listing_prices_one_primary
  ON public.listing_prices (listing_id)
  WHERE is_primary;

CREATE INDEX IF NOT EXISTS idx_listing_prices_listing_id
  ON public.listing_prices (listing_id);

CREATE TABLE IF NOT EXISTS public.listing_field_assertions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id TEXT NOT NULL REFERENCES public.watch_records(id) ON DELETE CASCADE,
  field_name TEXT NOT NULL,
  raw_value TEXT,
  normalized_value TEXT,
  confidence INTEGER,
  source_method TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_listing_field_assertions_listing_id
  ON public.listing_field_assertions (listing_id);

ALTER TABLE public.raw_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listing_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listing_field_assertions ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.raw_messages FROM anon, authenticated;
REVOKE ALL ON public.listing_prices FROM anon, authenticated;
REVOKE ALL ON public.listing_field_assertions FROM anon, authenticated;

GRANT ALL ON public.raw_messages TO service_role;
GRANT ALL ON public.listing_prices TO service_role;
GRANT ALL ON public.listing_field_assertions TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
