-- The production schema contains dealers and source identities but lacks the
-- four directory evidence tables introduced by 20260814203000. Restore only
-- these prerequisites before the September directory RPCs. No identities,
-- ratings, contact consent or listing links are inferred or populated here.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';

CREATE TABLE IF NOT EXISTS public.dealer_directory_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dealer_id uuid NOT NULL REFERENCES public.dealers(id) ON DELETE CASCADE,
  source_system text NOT NULL,
  source_profile_id text NOT NULL,
  captured_at timestamptz NOT NULL,
  source_rank integer,
  wts_count integer,
  wtb_count integer,
  group_count integer,
  review_count integer,
  positive_feedback_count integer,
  negative_feedback_count integer,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  imported_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_system, source_profile_id, captured_at)
);
CREATE TABLE IF NOT EXISTS public.dealer_reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dealer_id uuid NOT NULL REFERENCES public.dealers(id) ON DELETE CASCADE,
  source_system text NOT NULL,
  source_review_key text NOT NULL,
  reviewer_name text,
  review_date text,
  sentiment text,
  rating numeric(3,2),
  source_published boolean NOT NULL DEFAULT true,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (dealer_id, source_system, source_review_key)
);
CREATE TABLE IF NOT EXISTS public.dealer_group_memberships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dealer_id uuid NOT NULL REFERENCES public.dealers(id) ON DELETE CASCADE,
  source_system text NOT NULL,
  group_identity text NOT NULL,
  group_name text,
  platform text,
  membership_status text NOT NULL DEFAULT 'OBSERVED',
  source_published boolean NOT NULL DEFAULT false,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  first_seen_at timestamptz,
  last_seen_at timestamptz,
  UNIQUE (dealer_id, source_system, group_identity)
);
CREATE TABLE IF NOT EXISTS public.dealer_listing_links (
  listing_id uuid PRIMARY KEY,
  source_record_id text,
  dealer_id uuid NOT NULL REFERENCES public.dealers(id) ON DELETE RESTRICT,
  source_system text NOT NULL,
  source_identity text NOT NULL,
  link_method text NOT NULL CHECK (link_method IN ('EXACT_VERIFIED_PHONE', 'AUTHENTICATED_SUBMISSION')),
  link_status text NOT NULL DEFAULT 'APPLIED' CHECK (link_status IN ('APPLIED', 'REVOKED')),
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  linked_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_qnsa_dealer_listing_links_profile
  ON public.dealer_listing_links (dealer_id, link_status, listing_id);
ALTER TABLE public.dealer_directory_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dealer_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dealer_group_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dealer_listing_links ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.dealer_directory_snapshots, public.dealer_reviews,
  public.dealer_group_memberships, public.dealer_listing_links
  FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.dealer_directory_snapshots, public.dealer_reviews,
  public.dealer_group_memberships, public.dealer_listing_links TO service_role;
REVOKE ALL ON SEQUENCE public.dealer_directory_snapshots_id_seq,
  public.dealer_reviews_id_seq, public.dealer_group_memberships_id_seq
  FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.dealer_directory_snapshots_id_seq,
  public.dealer_reviews_id_seq, public.dealer_group_memberships_id_seq TO service_role;
COMMIT;
