WITH control AS MATERIALIZED (SELECT enabled_run_key FROM public.qnsa_two_brand_release_control WHERE canonical_brand='Rolex' AND trading_floor_enabled), base AS MATERIALIZED (
 SELECT l.id::text id,l.source_record_id,l.reference_normalized,(COALESCE(l.public_image_eligible,false) AND btrim(COALESCE(l.image_url,l.source_media_url_candidate,''))~*'^https?://[^[:space:]]+$') has_image,
 (COALESCE(l.price_normalized,l.price_original,l.price_usd,0)>0) has_price,(NULLIF(btrim(COALESCE(l.user_name,l.from_name,'')),'') IS NOT NULL) has_user
 FROM staging.listings l JOIN control c ON c.enabled_run_key=l.normalization_run_key WHERE l.brand_normalized='Rolex' AND upper(COALESCE(l.category,''))='WATCH' AND l.parent_id IS NULL AND COALESCE(l.is_bundle,false)=false
 AND upper(COALESCE(l.listing_type,l.intent,'')) IN ('WTS','WTB') AND COALESCE(l.provenance_metadata->>'bundle_status','SINGLE_CANDIDATE')='SINGLE_CANDIDATE'
 AND lower(COALESCE(l.trading_floor_status,'')) NOT IN ('bundle_child_pending_review','bundle_pending_separation','suppressed_exact_duplicate','withdrawn','rejected','hidden','deleted','archived') AND upper(COALESCE(l.verdict,'')) NOT IN ('WITHDRAWN','REJECTED','HIDDEN','DELETED','ARCHIVED')
), overlay AS MATERIALIZED (
 SELECT w.id,w.source_record_id,w.normalized_reference,(upper(COALESCE(w.image_evidence_type,''))='SELLER_LISTING_IMAGE' AND btrim(COALESCE(w.user_image_url,w.final_image_url,w.display_image_url,''))~*'^https?://[^[:space:]]+$') has_image,
 (COALESCE(w.source_price_amount,w.workbook_price_usd,0)>0) has_price,(NULLIF(btrim(COALESCE(w.posted_by,'')),'') IS NOT NULL) has_user
 FROM public.reviewed_workbook_inventory w WHERE w.brand_scope='Rolex' AND w.verification_tier='QNSA_ROLEX_PATEK_REVIEWED_DELTA_V1' AND w.confidence=100 AND w.source_message_id IS NOT NULL
 AND ((w.verification_status='APPROVED_SINGLE_CANDIDATE' AND (upper(COALESCE(w.listing_type,'')) IN ('WTS','WTB','OTHER') OR w.listing_type IS NULL)) OR (w.id='rpdelta_1ac10392cca161ba85a042a2f3efd4ef79cda691ccca2422f8b3280eebbf5972' AND w.verification_status='APPROVED_MULTI_PARENT_TRADING_FLOOR_ONLY' AND w.listing_type='MULTI'))
), combined AS MATERIALIZED (SELECT id,source_record_id,reference_normalized,has_image,has_price,has_user FROM base UNION ALL SELECT id,source_record_id,normalized_reference,has_image,has_price,has_user FROM overlay),
agg AS MATERIALIZED (SELECT count(*) total,count(*) FILTER(WHERE has_image) with_image,count(*) FILTER(WHERE NOT has_image) without_image,count(*) FILTER(WHERE has_price) with_price,count(*) FILTER(WHERE NOT has_price) without_price,count(*) FILTER(WHERE has_user) with_user,count(*) FILTER(WHERE NOT has_user) without_user,md5(count(*)::text||':'||COALESCE(sum(hashtextextended(id,0)::numeric),0)::text) checksum FROM combined),
refs AS MATERIALIZED (SELECT regexp_replace(upper(btrim(reference_normalized)),'[^A-Z0-9]','','g') ref_key FROM combined WHERE NULLIF(btrim(reference_normalized),'') IS NOT NULL GROUP BY 1),
dealer AS MATERIALIZED (SELECT b.id,(l.listing_id IS NOT NULL) linked,(d.rating IS NOT NULL AND d.review_count>0) rated FROM base b LEFT JOIN public.dealer_listing_links l ON l.listing_id=b.id::uuid AND l.link_status='APPLIED' LEFT JOIN public.dealers d ON d.id=l.dealer_id)
SELECT jsonb_build_object('contract','watchfacts-rolex-phase2-trading-floor-v1','project_ref','qnsafosakvonzgfcsphh','read_only',true,'transaction_read_only',current_setting('transaction_read_only'),'generated_at',now(),
'counts',jsonb_build_object('released_base_rows',(SELECT count(*) FROM base),'reviewed_overlay_rows',(SELECT count(*) FROM overlay),'exact_overlay_base_source_record_overlaps',(SELECT count(*) FROM overlay o JOIN base b ON b.source_record_id=o.source_record_id WHERE o.source_record_id IS NOT NULL),'trading_floor_listings',(SELECT total FROM agg),'trading_floor_references',(SELECT count(*) FROM refs),'listings_with_valid_real_images',(SELECT with_image FROM agg),'listings_without_images',(SELECT without_image FROM agg),'listings_with_any_positive_price',(SELECT with_price FROM agg),'listings_missing_price',(SELECT without_price FROM agg),'listings_with_posted_user',(SELECT with_user FROM agg),'listings_missing_posted_user',(SELECT without_user FROM agg),'base_listings_with_exact_dealer_link',(SELECT count(*) FROM dealer WHERE linked),'base_listings_missing_exact_dealer_link',(SELECT count(*) FROM dealer WHERE NOT linked),'base_listings_with_source_backed_dealer_rating',(SELECT count(*) FROM dealer WHERE rated),'base_listings_missing_source_backed_dealer_rating',(SELECT count(*) FROM dealer WHERE NOT rated)),
'reference_keys',(SELECT COALESCE(jsonb_agg(ref_key ORDER BY ref_key),'[]'::jsonb) FROM refs),'checksum',(SELECT checksum FROM agg)) AS trading_floor;
