'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),zlib=require('node:zlib'),crypto=require('node:crypto');
const {verifySpecificArchiveParents}=require('./expanded-reviewed-admissions-v4.cjs'),{stableJson}=require('./lossless-payload-sanitizer.cjs');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function fixture(t){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'wf-v4-archive-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));
 const raw=[{id:'source-a',title:'Original \u2028 source'},{id:'source-b',title:'Second source'}],lines=raw.map(stableJson),bytes=zlib.gzipSync(lines.join('\n')+'\n'),file='part.jsonl.gz';fs.writeFileSync(path.join(directory,file),bytes);
 const source={chunks:[{file,sha256:sha(bytes),rows:2}]},rows=raw.map((r,i)=>({source_id:r.id,source_hash:sha(lines[i]),raw_payload:r,original_source_pointer:{raw_chunk:file,raw_chunk_sha256:sha(bytes),row_index:i}})),policy=new Map(rows.map(r=>[r.source_id,{source_id:r.source_id,source_hash:r.source_hash}]));return{directory,source,rows,policy};}
test('exact archive bytes, IDs and canonical payloads bind both selected and unselected parents',async t=>{const f=fixture(t);assert.equal(await verifySpecificArchiveParents(f.rows.slice().reverse(),f.source,f.directory,f.policy),2);});
test('valid but wrong in-bounds archive pointer is rejected',async t=>{const f=fixture(t),bad=structuredClone(f.rows[0]);bad.original_source_pointer.row_index=1;await assert.rejects(verifySpecificArchiveParents([bad],f.source,f.directory,f.policy),/RAW_ARCHIVE_SOURCE_HASH_MISMATCH/);});
test('changed held-parent source hash cannot weaken the older-version exclusion barrier',async t=>{const f=fixture(t),bad=structuredClone(f.rows[1]);bad.source_hash='a'.repeat(64);await assert.rejects(verifySpecificArchiveParents([f.rows[0],bad],f.source,path.join(f.directory,'does-not-exist'),f.policy),e=>e.code==='ERR_ASSERTION'&&!String(e).includes('ENOENT'));});
test('changed archive bytes and reused pointers fail independently of packet hashes',async t=>{const f=fixture(t);await assert.rejects(verifySpecificArchiveParents([f.rows[0],f.rows[0]],f.source,f.directory,f.policy),/EXACT_ARCHIVE_POINTER_REUSED/);fs.appendFileSync(path.join(f.directory,'part.jsonl.gz'),'changed');await assert.rejects(verifySpecificArchiveParents(f.rows,f.source,f.directory,f.policy),/RAW_CHUNK_HASH_MISMATCH/);});
