'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),zlib=require('node:zlib'),crypto=require('node:crypto');
const gate=require('./expanded-reviewed-admissions-v2.cjs'),v1=require('./expanded-evidence-candidates.cjs'),v2=require('./expanded-evidence-candidates-v2.cjs');
const {stableJson}=require('./lossless-payload-sanitizer.cjs'),{findAnchorIssues}=require('./run-expanded-reference-anchor-corrections-v2.cjs');
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
function fixture(t){
 const tempRoot=path.resolve(os.tmpdir()),dir=fs.mkdtempSync(path.join(tempRoot,'wf-mixed-admissions-'));
 t.after(()=>{const rel=path.relative(tempRoot,dir);assert.ok(rel.startsWith('wf-mixed-admissions-')&&!rel.includes(path.sep));fs.rmSync(dir,{recursive:true,force:true});});
 const bind=(name,bytes)=>{const file=path.join(dir,name);fs.writeFileSync(file,bytes);return{file,sha256:sha(bytes)};},doc=(name,x)=>bind(name,JSON.stringify(x)),gzip=(name,rows)=>({...bind(name,zlib.gzipSync(rows.map(stableJson).join('\n')+'\n')),rows:rows.length});
 const raw=[{id:'A',title:'WTS Rolex 116500LN asking USD 25000',type:'sale',is_bundle:0},{id:'B',title:'WTB Rolex 114300\nRef:39mm\nUsed with card',type:'sale',is_bundle:0,front_image:'exact-original.jpg'}];
 const chunk=gzip('raw.jsonl.gz',raw),source={source_system:'FIXTURE',source_database:'test',source_table:'auctions',rows:2,manifest_sha256:'a'.repeat(64),chunks:[{file:'raw.jsonl.gz',sha256:chunk.sha256,rows:2}]},sourceRef=doc('source.json',source);
 const staged=raw.map(r=>({source_id:r.id,source_hash:sha(stableJson(r)),raw_payload:r,source_system:source.source_system,source_database:source.source_database,source_table:source.source_table,canonicalization_version:'v1-json-keys-sorted-compact',hash_algorithm:'sha256'}));
 const wrap=(e,i)=>({source_id:raw[i].id,source_hash:staged[i].source_hash,raw_chunk:'raw.jsonl.gz',raw_chunk_sha256:chunk.sha256,row_index:i,candidate_hash:e.candidate_hash,candidate:e.candidate});
 const old=staged.map((s,i)=>v1.buildExpandedCandidates(s).candidates.map(e=>wrap(e,i))),next=v2.buildExpandedCandidates(staged[1]).candidates.map(e=>wrap(e,1));assert.equal(next.length,1);
 const frozen={contract:'WF_EXPANDED_LOCAL_DRY_RUN_V1',status:'PASS_COMPLETE_LOCAL_EXPANDED_CANDIDATE_DRY_RUN',parent_rows:2,binding:{source_manifest_file_sha256:sourceRef.sha256,source_manifest_sha256:source.manifest_sha256,parser_sha256:sha(fs.readFileSync(path.join(__dirname,'expanded-evidence-candidates.cjs'))),runner_sha256:sha(fs.readFileSync(path.join(__dirname,'run-expanded-local-dry-run.cjs'))),dependencies:v1.DEPENDENCY_HASHES},parts:old.map((rows,i)=>({candidates:gzip(i+'.old.gz',rows)}))};
 const parent={source_id:'B',source_hash:staged[1].source_hash,original_parser_part_index:1,original_candidate_hashes:old[1].map(e=>e.candidate_hash),repaired_candidate_hashes:next.map(e=>e.candidate_hash),issues:old[1].flatMap(e=>findAnchorIssues(e.candidate).map(issue=>({...issue,original_candidate_hash:e.candidate_hash})))};
 const correction={contract:'WF_EXPANDED_REFERENCE_ANCHOR_CORRECTIONS_V2',status:'COMPLETE_LOCAL_CORRECTION_REBUILD_PENDING_REVIEW',base_parser_manifest:doc('base.json',frozen),binding:{source_manifest:sourceRef,base_binding:frozen.binding,parser_files:Object.fromEntries(['expanded-evidence-candidates.cjs','expanded-evidence-candidates-v2.cjs','expanded-reference-anchor-policy-v2.cjs','run-expanded-reference-anchor-corrections-v2.cjs'].map(f=>[f,sha(fs.readFileSync(path.join(__dirname,f)))]))},processed_parts:frozen.parts.map((p,i)=>({original_parser_part_index:i,original_candidates:p.candidates})),correction_parts:[{original_parser_part_index:1,original_candidates:frozen.parts[1].candidates,candidates:gzip('corrected.gz',next),affected_parents:gzip('parents.gz',[parent])}],counts:{affected_parents:1}};
 const policies={[v1.PARSER_VERSION]:'1'.repeat(64),[v2.PARSER_VERSION]:'2'.repeat(64)};
 const select=rows=>rows.map(r=>({candidate_hash:r.candidate_hash,source_hash:r.source_hash}));
 const review={contract:gate.CONTRACT,status:gate.SEALED,parser_manifest:correction.base_parser_manifest,source_manifest:sourceRef,correction_manifest:doc('correction.json',correction),parser_registry:Object.fromEntries([[v1,'expanded-evidence-candidates.cjs'],[v2,'expanded-evidence-candidates-v2.cjs']].map(([p,f])=>[p.PARSER_VERSION,{policy_hash:policies[p.PARSER_VERSION],parser_sha256:sha(fs.readFileSync(path.join(__dirname,f))),dependency_hashes:p.DEPENDENCY_HASHES}])),parts:[{parser_part_index:0,selection:gzip('base-select.gz',select(old[0]))}],correction_parts:[{correction_part_index:0,original_parser_part_index:1,selection:gzip('correction-select.gz',select(next))}],selected_candidate_count:2};
 let pointer;function seal(){correction.correction_parts[0].candidates=gzip('corrected.gz',next);correction.correction_parts[0].affected_parents=gzip('parents.gz',[parent]);review.correction_manifest=doc('correction.json',correction);pointer=doc('review.json',review);}seal();
 async function run(){const rows=[];const receipt=await gate.verifyReviewedAdmissionsV2({reviewManifestFile:pointer.file,expectedReviewManifestSha256:pointer.sha256,policyHashes:policies,onAdmission:async r=>rows.push(r)});return{rows,receipt,globalSha:pointer.sha256};}
 return{run,seal,old,next,parent,review,correction,policies,gzip,select};
}
test('mixed registered versions preserve exact facts and emit only the global reviewed SHA',async t=>{const f=fixture(t),r=await f.run();assert.equal(r.receipt.verified_admissions,2);assert.deepEqual(r.rows.map(x=>x.policy_hash),['1'.repeat(64),'2'.repeat(64)]);assert.ok(r.rows.every(x=>x.review_manifest_sha256===r.globalSha));assert.equal(f.next[0].candidate.kind,'SINGLE');assert.deepEqual(f.next[0].candidate.images.source_image_keys,['exact-original.jpg']);});
test('old affected siblings cannot be selected, even if their manifest hash list is omitted',async t=>{const f=fixture(t);f.review.parts.push({parser_part_index:1,selection:f.gzip('bad-base.gz',f.select([f.old[1][0]]))});f.parent.original_candidate_hashes=[];f.review.selected_candidate_count++;f.seal();await assert.rejects(f.run(),/SUPERSEDED_V1_CANDIDATE_SELECTED/);});
for(const field of ['brand','currency','image'])test('self-rehashed correction '+field+' cannot authorize fabricated facts',async t=>{const f=fixture(t),r=f.next[0];if(field==='brand')r.candidate.fields.brand='Patek Philippe';if(field==='currency')r.candidate.fields.original_price_currency='USD';if(field==='image')r.candidate.images.source_image_keys=['invented.jpg'];r.candidate_hash=sha(stableJson(r.candidate));f.parent.repaired_candidate_hashes=[r.candidate_hash];f.review.correction_parts[0].selection=f.gzip('forged-select.gz',f.select(f.next));f.seal();await assert.rejects(f.run(),/CORRECTION_REBUILT_PARENT_PROOF_MISMATCH/);});
test('false repair reasons cannot authorize an otherwise exact candidate',async t=>{const f=fixture(t);f.parent.issues[0].quote='invented';f.seal();await assert.rejects(f.run(),/CORRECTION_ROLE_EVIDENCE_MISMATCH/);});
test('complete immutable base and complete correction are both mandatory',async t=>{const f=fixture(t);f.correction.status='PASS_COMPLETED_PREFIX_PENDING_FULL_SOURCE';f.seal();await assert.rejects(f.run(),/CORRECTION_NOT_COMPLETE/);});
test('a different policy registry cannot substitute for root supplied version policies',async t=>{const f=fixture(t);f.review.parser_registry[v2.PARSER_VERSION].policy_hash='3'.repeat(64);f.seal();await assert.rejects(f.run(),/POLICY_HASH_MISMATCH/);});
test('duplicate or wrongly bound correction parts are rejected',async t=>{const f=fixture(t);f.review.correction_parts[0].original_parser_part_index=0;f.seal();await assert.rejects(f.run());});
