'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),zlib=require('node:zlib'),crypto=require('node:crypto');
const gate=require('./expanded-reviewed-admissions-v3.cjs'),v1=require('./expanded-evidence-candidates.cjs'),v2=require('./expanded-evidence-candidates-v2.cjs'),v3=require('./expanded-evidence-candidates-v3.cjs');
const {stableJson}=require('./lossless-payload-sanitizer.cjs'),{findAnchorIssues}=require('./run-expanded-reference-anchor-corrections-v2.cjs');
const sha=x=>crypto.createHash('sha256').update(x).digest('hex'),fileHash=f=>sha(fs.readFileSync(path.join(__dirname,f)));
function fixture(t){
 const temp=path.resolve(os.tmpdir()),dir=fs.mkdtempSync(path.join(temp,'wf-three-admissions-'));t.after(()=>{const rel=path.relative(temp,dir);assert.ok(rel.startsWith('wf-three-admissions-')&&!rel.includes(path.sep));fs.rmSync(dir,{recursive:true,force:true});});
 const bind=(name,b)=>{const file=path.join(dir,name);fs.writeFileSync(file,b);return{file,sha256:sha(b)};},doc=(name,v)=>bind(name,JSON.stringify(v)),gzip=(name,rows)=>({...bind(name,zlib.gzipSync(rows.map(stableJson).join('\n')+'\n')),rows:rows.length});
 const raw=[{id:'A',title:'WTS Rolex 116500LN asking USD 25000',type:'sale',is_bundle:0},{id:'B',title:'WTB Rolex 114300\nRef:39mm\nUsed with card',type:'sale',is_bundle:0,front_image:'exact-original.jpg'},{id:'C',title:'Rolex\n336238 black 323000 hkd 2025-9 🏷️\n128348rbr-0069 green 880000 hkd 2025-11 🏷️\nRef:39mm',type:'sale',is_bundle:0,front_image:'parent-image.jpg'}];
 const chunk=gzip('raw.gz',raw),source={source_system:'FIXTURE',source_database:'test',source_table:'auctions',rows:raw.length,manifest_sha256:'a'.repeat(64),chunks:[{file:'raw.gz',sha256:chunk.sha256,rows:raw.length}]},sourceRef=doc('source.json',source);
 const staged=raw.map(r=>({source_id:r.id,source_hash:sha(stableJson(r)),raw_payload:r,source_system:source.source_system,source_database:source.source_database,source_table:source.source_table,canonicalization_version:'v1-json-keys-sorted-compact',hash_algorithm:'sha256'}));
 const wrap=(e,i)=>({source_id:raw[i].id,source_hash:staged[i].source_hash,raw_chunk:'raw.gz',raw_chunk_sha256:chunk.sha256,row_index:i,candidate_hash:e.candidate_hash,candidate:e.candidate});
 const a=staged.map((s,i)=>v1.buildExpandedCandidates(s).candidates.map(e=>wrap(e,i))),b=staged.map((s,i)=>v2.buildExpandedCandidates(s).candidates.map(e=>wrap(e,i))),c=v3.buildExpandedCandidates(staged[2]).candidates.map(e=>wrap(e,2));assert.equal(c.length,2);assert.equal(c[0].candidate.decision.trading_floor,'TF_SUPPORTED_CANDIDATE');assert.equal(c[1].candidate.decision.trading_floor,'REVIEW');
 const frozen={contract:'WF_EXPANDED_LOCAL_DRY_RUN_V1',status:'PASS_COMPLETE_LOCAL_EXPANDED_CANDIDATE_DRY_RUN',parent_rows:raw.length,binding:{source_manifest_file_sha256:sourceRef.sha256,source_manifest_sha256:source.manifest_sha256,parser_sha256:fileHash('expanded-evidence-candidates.cjs'),runner_sha256:fileHash('run-expanded-local-dry-run.cjs'),dependencies:v1.DEPENDENCY_HASHES},parts:a.map((r,i)=>({candidates:gzip('old-'+i+'.gz',r)}))},baseRef=doc('base.json',frozen);
 const previousParents=[1,2].map(i=>({source_id:raw[i].id,source_hash:staged[i].source_hash,original_parser_part_index:i,original_candidate_hashes:a[i].map(e=>e.candidate_hash),repaired_candidate_hashes:b[i].map(e=>e.candidate_hash),issues:a[i].flatMap(e=>findAnchorIssues(e.candidate).map(issue=>({...issue,original_candidate_hash:e.candidate_hash})))}));
 const previous={contract:'WF_EXPANDED_REFERENCE_ANCHOR_CORRECTIONS_V2',status:'COMPLETE_LOCAL_CORRECTION_REBUILD_PENDING_REVIEW',base_parser_manifest:baseRef,binding:{source_manifest:sourceRef,base_binding:frozen.binding,parser_files:Object.fromEntries(['expanded-evidence-candidates.cjs','expanded-evidence-candidates-v2.cjs','expanded-reference-anchor-policy-v2.cjs','run-expanded-reference-anchor-corrections-v2.cjs'].map(f=>[f,fileHash(f)]))},processed_parts:frozen.parts.map((p,i)=>({original_parser_part_index:i,original_candidates:p.candidates})),correction_parts:[1,2].map((i,j)=>({original_parser_part_index:i,original_candidates:frozen.parts[i].candidates,candidates:gzip('v2-'+i+'.gz',b[i]),affected_parents:gzip('v2-parent-'+i+'.gz',[previousParents[j]])})),counts:{affected_parents:2}};
 const parent={source_id:'C',source_hash:staged[2].source_hash,original_parser_part_index:2,original_candidate_hashes:a[2].map(e=>e.candidate_hash),previous_v2_candidate_hashes:b[2].map(e=>e.candidate_hash),repaired_candidate_hashes:c.map(e=>e.candidate_hash),issues:gate.scopeIssues(a[2]),supersedes_all_older_candidates_for_parent:true};
 const correction={contract:'WF_EXPANDED_SOURCE_SCOPE_CORRECTIONS_V3',status:'COMPLETE_LOCAL_CORRECTION_REBUILD_PENDING_REVIEW',supersession:'ALL_OLDER_V1_AND_V2_CANDIDATES_OF_EACH_AFFECTED_PARENT',base_parser_manifest:baseRef,binding:{source_manifest:sourceRef,base_binding:frozen.binding,parser_files:Object.fromEntries(['expanded-evidence-candidates.cjs','expanded-evidence-candidates-v2.cjs','expanded-evidence-candidates-v3.cjs','expanded-reference-anchor-policy-v2.cjs','expanded-source-scope-policy-v3.cjs','run-expanded-source-scope-corrections-v3.cjs'].map(f=>[f,fileHash(f)]))},processed_parts:previous.processed_parts,correction_parts:[{original_parser_part_index:2,original_candidates:frozen.parts[2].candidates,candidates:gzip('v3.gz',c),affected_parents:gzip('v3-parent.gz',[parent])}],counts:{affected_parents:1}};
 const parsers=[[v1,'expanded-evidence-candidates.cjs'],[v2,'expanded-evidence-candidates-v2.cjs'],[v3,'expanded-evidence-candidates-v3.cjs']],policies=Object.fromEntries(parsers.map(([p],i)=>[p.PARSER_VERSION,String(i+1).repeat(64)])),select=rs=>rs.map(r=>({candidate_hash:r.candidate_hash,source_hash:r.source_hash}));
 const review={contract:gate.CONTRACT,status:gate.SEALED,parser_manifest:baseRef,source_manifest:sourceRef,correction_manifest:doc('previous.json',previous),scope_correction_manifest:null,parser_registry:Object.fromEntries(parsers.map(([p,f])=>[p.PARSER_VERSION,{policy_hash:policies[p.PARSER_VERSION],parser_sha256:fileHash(f),dependency_hashes:p.DEPENDENCY_HASHES}])),parts:[{parser_part_index:0,selection:gzip('select-v1.gz',select(a[0]))}],correction_parts:[{correction_part_index:0,original_parser_part_index:1,selection:gzip('select-v2.gz',select(b[1]))}],scope_correction_parts:[{correction_part_index:0,original_parser_part_index:2,selection:gzip('select-v3.gz',select([c[0]]))}],selected_candidate_count:3};
 let pointer;function seal(){correction.correction_parts[0].candidates=gzip('v3.gz',c);correction.correction_parts[0].affected_parents=gzip('v3-parent.gz',[parent]);review.scope_correction_manifest=doc('scope.json',correction);pointer=doc('review.json',review);}seal();
 async function run(){const rows=[];const receipt=await gate.verifyReviewedAdmissionsV3({reviewManifestFile:pointer.file,expectedReviewManifestSha256:pointer.sha256,policyHashes:policies,onAdmission:async r=>rows.push(r)});return{receipt,rows,globalSha:pointer.sha256};}
 return{run,seal,a,b,c,parent,review,correction,previous,policies,gzip,select};
}
test('three source policies emit only one global reviewed selection hash',async t=>{const f=fixture(t),r=await f.run();assert.equal(r.receipt.verified_admissions,3);assert.deepEqual(r.rows.map(x=>x.policy_hash),['1'.repeat(64),'2'.repeat(64),'3'.repeat(64)]);assert.ok(r.rows.every(x=>x.review_manifest_sha256===r.globalSha));});
test('a V2 sibling of a V3 parent is rejected even if old candidate hash lists are omitted',async t=>{const f=fixture(t);f.parent.original_candidate_hashes=[];f.parent.previous_v2_candidate_hashes=[];f.review.correction_parts.push({correction_part_index:1,original_parser_part_index:2,selection:f.gzip('bad-older.gz',f.select([f.b[2][0]]))});f.review.selected_candidate_count++;f.seal();await assert.rejects(f.run(),/SUPERSEDED_OLDER_PARENT_CANDIDATE_SELECTED/);});
test('V1 siblings cannot coexist with their V3 parent replacement',async t=>{const f=fixture(t);f.review.parts.push({parser_part_index:2,selection:f.gzip('bad-original.gz',f.select([f.a[2][0]]))});f.review.selected_candidate_count++;f.seal();await assert.rejects(f.run(),/SUPERSEDED_V1_CANDIDATE_SELECTED|SUPERSEDED_OLDER_PARENT_CANDIDATE_SELECTED/);});
test('an unverified full-suffix reference stays held even when exactly reconstructed',async t=>{const f=fixture(t);f.review.scope_correction_parts[0].selection=f.gzip('held.gz',f.select(f.c));f.review.selected_candidate_count++;f.seal();await assert.rejects(f.run(),/SCOPE_CANDIDATE_HELD/);});
for(const field of ['brand','currency','image'])test('self-rehashed V3 '+field+' cannot bypass source reconstruction',async t=>{const f=fixture(t),r=f.c[0];if(field==='brand')r.candidate.fields.brand='Patek Philippe';if(field==='currency')r.candidate.fields.original_price_currency='USD';if(field==='image')r.candidate.images.image_url='invented.jpg';r.candidate_hash=sha(stableJson(r.candidate));f.parent.repaired_candidate_hashes=f.c.map(x=>x.candidate_hash);f.review.scope_correction_parts[0].selection=f.gzip('forged.gz',f.select([r]));f.seal();await assert.rejects(f.run(),/SCOPE_REBUILT_PARENT_PROOF_MISMATCH/);});
test('false scope evidence is rejected independently of exact new candidate bytes',async t=>{const f=fixture(t);f.parent.issues[0].quote='invented';f.seal();await assert.rejects(f.run(),/SCOPE_REASON_EVIDENCE_MISMATCH/);});
test('complete third correction census is mandatory',async t=>{const f=fixture(t);f.correction.status='PASS_COMPLETED_PREFIX_PENDING_FULL_SOURCE';f.seal();await assert.rejects(f.run(),/CORRECTION_NOT_COMPLETE/);});
test('wrong third registry cannot substitute a policy',async t=>{const f=fixture(t);f.review.parser_registry[v3.PARSER_VERSION].policy_hash='4'.repeat(64);f.seal();await assert.rejects(f.run(),/POLICY_HASH_MISMATCH/);});
test('V3-only selection still validates both complete historical correction manifests',async t=>{const f=fixture(t);f.review.parts=[];f.review.correction_parts=[];f.review.selected_candidate_count=1;f.seal();const r=await f.run();assert.equal(r.receipt.verified_admissions,1);assert.equal(r.receipt.older_proof,null);assert.equal(r.rows[0].policy_hash,'3'.repeat(64));});

