'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {stableJson}=require('./lossless-payload-sanitizer.cjs');
const {proposeExistingEnrichment:propose,sameAmount}=require('./expanded-existing-enrichment.cjs');
function fixture(){const raw={id:'a',description:'WTS Rolex 126610LN USD 10000',status:'ended',created_on:'2025-01-02 10:00:00',deleted_on:null,region:'Europe'};const staged={id:'raw-uuid',source_id:'a',source_hash:crypto.createHash('sha256').update(stableJson(raw)).digest('hex'),source_system:'OceanDigital MariaDB',source_database:'d',source_table:'auctions',raw_payload:raw,canonicalization_version:'v1-json-keys-sorted-compact',hash_algorithm:'sha256'};
 const current={listing_id:'WF-a',source_id:'a',source_hash:staged.source_hash,raw_message_id:'raw-uuid',raw_message_text:raw.description,parent_listing_id:null,child_index:null,is_bundle:false,category:'WATCH',brand:'Rolex',reference:'126610LN',intent:'WTS',model:'Submariner',year:2024,condition:null,dial_color:null,original_price_text:null,original_price_amount:null,original_price_currency:null,price_usd:null,price_status:'PRICE_NOT_SUPPLIED',price_research_eligible:false,included_in_statistics:false,statistics_exclusion_reason:'PRICE_NOT_SUPPLIED',image_url:'https://original.example/a',thumbnail_url:'https://original.example/a',image_key:'a'};
 const candidate={source_id:'a',source_hash:staged.source_hash,kind:'SINGLE',decision:{trading_floor:'TF_SUPPORTED_CANDIDATE',reasons:[]},fields:{brand:current.brand,reference:current.reference,intent:current.intent,model:null,year:2023,condition:'Brand new',dial_color:'Black',original_price_amount:'10000',original_price_currency:'USD',original_price_role:'WTS_ASK'}};
 const materialized={...current,original_price_text:'USD 10000',original_price_amount:10000,original_price_currency:'USD',original_price_role:'WTS_ASK',price_usd:10000,fx_rate:1,fx_source:'1:1_PARITY_PROOF',fx_date:'2026-09-07',price_status:'VERIFIED_USD',price_research_eligible:true,included_in_statistics:true,statistics_exclusion_reason:null};return{current,staged,candidate,materialized};}
test('metadata adds explicit historical status and wall-clock text without a guessed timezone',()=>{const f=fixture(),before=stableJson(f.staged);const r=propose({...f,candidate:null,materialized:null});assert.equal(r.patch.source_listing_status,'ended');assert.equal(r.patch.source_deleted,false);assert.equal(r.patch.source_created_at_text,'2025-01-02 10:00:00');assert.equal(r.patch.source_created_at,undefined);assert.equal(r.patch.location_country,undefined);assert.equal(r.patch.location_region,'Europe');assert.equal(stableJson(f.staged),before);});
test('adds supported null fields while preserving stronger current model/year/image/raw',()=>{const f=fixture(),r=propose(f);assert.equal(r.after.model,'Submariner');assert.equal(r.after.year,2024);assert.ok(r.review_reasons.includes('year'));assert.equal(r.patch.condition,'Brand new');assert.equal(r.patch.dial_color,'Black');assert.equal(r.after.image_url,f.current.image_url);assert.equal(r.after.raw_message_text,f.current.raw_message_text);assert.equal(r.patch.price_usd,10000);assert.equal(r.patch.price_research_eligible,true);});
test('conflicting exact asking price stays unchanged and is reported',()=>{const f=fixture();f.current.original_price_amount='10000.01';f.current.original_price_currency='USD';const r=propose(f);assert.ok(r.review_reasons.includes('ORIGINAL_PRICE_CONFLICT'));assert.equal(r.patch.original_price_amount,undefined);assert.equal(r.patch.price_usd,undefined);});
test('existing USD/FX evidence never gets replaced by a new valuation',()=>{const f=fixture();Object.assign(f.current,{original_price_amount:'10000',original_price_currency:'USD',price_usd:9999,fx_rate:0.9999,fx_source:'old-verified',fx_date:'2025-01-02',price_research_eligible:true,included_in_statistics:true});const r=propose(f);assert.equal(r.after.price_usd,9999);assert.equal(r.after.fx_source,'old-verified');assert.equal(r.patch.original_price_role,'WTS_ASK');});
test('unresolved original currency retains amount without research admission',()=>{const f=fixture();f.candidate.fields.original_price_currency=null;Object.assign(f.materialized,{original_price_currency:null,price_usd:null,fx_rate:null,fx_source:null,fx_date:null,price_status:'UNRESOLVED_CURRENCY',price_research_eligible:false,included_in_statistics:false,statistics_exclusion_reason:'UNRESOLVED_CURRENCY'});const r=propose(f);assert.equal(r.patch.original_price_amount,10000);assert.equal(r.after.original_price_currency,null);assert.equal(r.after.price_usd,null);assert.equal(r.after.price_research_eligible,false);});
test('mismatched or child candidates cannot enrich existing watch facts',()=>{for(const mutation of [f=>{f.candidate.kind='CHILD';},f=>{f.candidate.fields.reference='Other';}]){const f=fixture();mutation(f);const r=propose(f);assert.ok(r.review_reasons.includes('CANDIDATE_IDENTITY_OR_SCOPE_REQUIRES_REVIEW'));assert.equal(r.patch.original_price_amount,undefined);assert.equal(r.patch.dial_color,undefined);}});
test('raw tampering and a changed raw UUID fail before proposal',()=>{const f=fixture();f.staged.raw_payload.description='changed';assert.throws(()=>propose(f));const g=fixture();g.current.raw_message_id='other';assert.throws(()=>propose(g));});
test('decimal cents remain distinct without binary floating conversion',()=>{assert.equal(sameAmount('010000.00',10000),true);assert.equal(sameAmount('10000.01','10000.00'),false);assert.equal(sameAmount('10000.000000000000001','10000'),false);});
