'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {stableJson}=require('./lossless-payload-sanitizer.cjs');
const {importReviewedExpandedSourceCompanies:importer}=require('./reviewed-expanded-source-company-import.cjs');
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
function fixture(sourceVerified=false){
 const source={id:'00000000-0000-4000-8000-000000000001',company_id:1,from_number:'+14155550123',from_name:'Fixture Poster',title:'WTS Rolex 126610LN asking USD 10000'};
 const rawText=stableJson(source),raw={id:'00000000-0000-4000-8000-000000000002',source_id:source.id,source_hash:sha(rawText),raw_payload_text:rawText,raw_payload:source,source_system:'OceanDigital MariaDB',source_database:'thecollective_inventory',source_table:'auctions',canonicalization_version:'v1-json-keys-sorted-compact',hash_algorithm:'sha256'};
 const company={id:1,name:'Fixture Poster',nickname:null,phone:'+14155550123',full_phone:'+14155550123',is_banned:0,is_suspended:0,is_active:1,is_verified:sourceVerified?1:0,status:sourceVerified?'verified':'unverified'};
 const snapshotBytes=Buffer.from(JSON.stringify({contract:'WF_SOURCE_COMPANY_IDENTITY_FIELD_SNAPSHOT_V1',source_database:'thecollective',source_table:'companies',observed_at:'2026-09-07T01:00:00Z',capture_scope:'COMPLETE_TABLE',expected_rows:1,companies:[company]})),expectedSnapshotSha256=sha(snapshotBytes);
 const attestation={contract:'WF_OWNER_ATTESTED_EXPANDED_POSTER_CONTACT_PERMISSION_V3',permission_inferred:false,scope:'Exact source-linked posters of reviewed supported single-watch listings and unbundled watch children',company_snapshot_sha256:expectedSnapshotSha256,recorded_at:'2026-09-08T18:00:00Z',owner_statement:'Synthetic explicit owner permission for this fixture',purpose:'Source-linked profiles and contact links'};
 const permission=()=>{const bytes=Buffer.from(JSON.stringify(attestation));return{bytes,sha256:sha(bytes)};};
 const selected={company_id:'1',phone:'14155550123',company_fields_sha256:sha(stableJson(company)),source_system:raw.source_system,source_database:raw.source_database,source_table:raw.source_table,first_source_id:raw.source_id,first_source_hash:raw.source_hash,candidate_hash:'a'.repeat(64),review_manifest_sha256:'b'.repeat(64)};
 const accepted={raw_row_id:raw.id,source_hash:raw.source_hash,kind:'CHILD',policy_hash:'c'.repeat(64),canonical_json:'{}',review_manifest_sha256:selected.review_manifest_sha256,candidate:{decision:{trading_floor:'TF_SUPPORTED_CANDIDATE'}}};
 const writes=[];let admissionPresent=true;
 const db={query:async(sql,args)=>{if(sql.includes('FROM wf_canonical_staging.mariadb_raw_source_rows'))return{rows:[raw]};if(sql.includes('FROM wf_canonical_staging.expanded_listing_candidates_v3'))return{rows:admissionPresent?[accepted]:[]};if(sql.trim().startsWith('SELECT'))return{rows:[]};writes.push({sql,args});return{rows:[],rowCount:1};}};
 return{attestation,selected,accepted,writes,db,raw,permission,options:()=>({snapshotBytes,expectedSnapshotSha256,identities:[selected],sourcePosterPermission:permission()}),setMissing:()=>{admissionPresent=false;}};
}
test('expanded source importer does not repurpose the old single-only permission',async()=>{const f=fixture();f.attestation.contract='WF_OWNER_ATTESTED_POSTER_CONTACT_PERMISSION_V1';f.attestation.scope='All exact source-linked posters of eligible single listings';await assert.rejects(importer(f.db,f.options()),/COMPANY_IMPORT_PERMISSION_SCOPE_INVALID/);assert.equal(f.writes.length,0);});
test('a raw bundle and directory identity alone do not admit a dealer',async()=>{const f=fixture();f.setMissing();await assert.rejects(importer(f.db,f.options()),/EXPANDED_COMPANY_IMPORT_ADMISSION_MISSING/);assert.equal(f.writes.length,0);});
test('candidate from another source parent or unreviewed manifest cannot grant contact identity',async()=>{for(const mutate of [f=>{f.accepted.raw_row_id=f.raw.source_id;},f=>{f.accepted.review_manifest_sha256='d'.repeat(64);},f=>{f.accepted.kind='BUNDLE';}]){const f=fixture();mutate(f);await assert.rejects(importer(f.db,f.options()),/EXPANDED_COMPANY_IMPORT_ADMISSION_SCOPE_MISMATCH/);assert.equal(f.writes.length,0);}});
test('admitted same-parent child binds the new owner scope without inventing reviews or dealer verification',async()=>{const f=fixture(),r=await importer(f.db,f.options());assert.equal(r.created_dealers,1);const dealer=f.writes.find(x=>x.sql.includes('INSERT INTO public.dealers'));assert.equal(dealer.args[3],'UNVERIFIED');assert.equal(dealer.args[4],true);const meta=dealer.args[6];assert.equal(meta.expanded_listing_evidence.candidate_hash,f.selected.candidate_hash);assert.equal(meta.expanded_listing_evidence.kind,'CHILD');assert.equal(meta.contact_permission_evidence.contract,f.attestation.contract);assert.equal(meta.reviews_inferred,false);assert.equal(meta.dealer_verification_inferred,false);assert.equal(f.writes.some(x=>x.sql.includes('mariadb_canary_published_listings')),false);});
test('source-verified company does not become ineligible for a consented source-poster link or gain an automatic dealer badge',async()=>{const f=fixture(true),r=await importer(f.db,f.options());assert.equal(r.created_dealers,1);assert.equal(f.writes.find(x=>x.sql.includes('INSERT INTO public.dealers')).args[3],'UNVERIFIED');});

function whitespaceFixture(){const f=fixture();f.raw.raw_payload.from_name='  Top Watches & Rolex & AP&patak\nFarid\t';f.raw.raw_payload_text=stableJson(f.raw.raw_payload);f.raw.source_hash=sha(f.raw.raw_payload_text);f.selected.first_source_hash=f.raw.source_hash;f.accepted.source_hash=f.raw.source_hash;f.selected.public_name_review={contract:'WF_EXACT_SOURCE_POSTER_WHITESPACE_REVIEW_V3',source_field:'from_name',raw_row_id:f.raw.id,source_id:f.raw.source_id,source_hash:f.raw.source_hash,source_text_sha256:sha(f.raw.raw_payload.from_name),normalized_name:'Top Watches & Rolex & AP&patak Farid',review_packet_sha256:'e'.repeat(64)};return f;}
test('reviewed source-poster whitespace normalizes only whitespace and preserves full original proof without a company claim',async()=>{const f=whitespaceFixture(),original=f.raw.raw_payload_text;await importer(f.db,f.options());const d=f.writes.find(x=>x.sql.includes('INSERT INTO public.dealers'));assert.equal(d.args[2],'Top Watches & Rolex & AP&patak Farid');assert.equal(d.args[3],'UNVERIFIED');assert.equal(d.args[7],null);assert.deepEqual(d.args[6].public_name_review,f.selected.public_name_review);assert.equal(f.raw.raw_payload_text,original);});
test('source-poster whitespace proof rejects spelling changes, changed source hash and use of the literal-only role',async()=>{for(const mutate of[f=>{f.selected.public_name_review.normalized_name='Top Watches & Rolex & AP&Patek Farid';},f=>{f.selected.public_name_review.source_text_sha256='f'.repeat(64);},f=>{f.selected.public_name_review.contract='WF_EXACT_SOURCE_POSTER_LABEL_REVIEW_V3';}]){const f=whitespaceFixture();mutate(f);await assert.rejects(importer(f.db,f.options()),/COMPANY_IMPORT_PUBLIC_NAME_PROOF_MISMATCH/);assert.equal(f.writes.length,0);}});
